### ISSUE TITLE
ERROR in Entry module not found: Error: Cannot resolve 'file' or 'directory'

### ISSUE THREAD

**Issue by irudym** [rails/webpacker#1006]
Hello, 

Run freshly installed webpack by the following command : 
**./bin/webpack --colors --progress**  

gets error:
_ERROR in Entry module not found: Error: Cannot resolve 'file' or 'directory' /home/igor/develop/fennec-core/app/javascript/packs/application.js in /home/igor/develop/fennec-core_

by running webpack with **--display-error-details** gets more strange details:
_/home/igor/develop/fennec-core/app/javascript/packs/application.js/package.json doesn't exist (directory description file)
  /home/igor/develop/fennec-core/app/javascript/packs/application.js is not a directory (directory default file)_

it seems that webpack treats application.js as a directory. However while running Storybook (from Kadira) everything works fine.

**Comment by gauravtiwari** [comment]
Could you please post an example repo to reproduce this?

**Comment by irudym** [comment]
gauravtiwari: Hi, sure:
https://github.com/irudym/fennec-core

**Comment by irudym** [comment]
the issue appeared after "@kadira/storybook": "^2.21.0" installed.

**Comment by gauravtiwari** [comment]
Seems to work fine, even with 2.35.3

![screen shot 2017-11-15 at 16 23 45](https://user-images.githubusercontent.com/771039/32847321-959eb1ae-ca21-11e7-8444-8cfc7760cccc.png)

**Comment by andrew-aladev** [comment]
This issue still exists. I will provide detailed info later.

**Comment by gauravtiwari** [comment]
Please do 👍

**Comment by andrew-aladev** [comment]
`node_modules/enhanced-resolve/lib/DirectoryDescriptionFilePlugin.js:19`:

```
directory: app/assets/javascripts/packs/application.js
filename:  package.json
```

So we can see that DirectoryDescriptionFilePlugin is not a suitable plugin for detecting whether file exist.

`node_modules/tapable/lib/Tapable.js:119`:

Here we can see 2 plugins in `plugins`: `DirectoryExistsPlugin` and `DirectoryDescriptionFilePlugin`. Both plugins couldn't detect existing file `application.js`.

**Comment by andrew-aladev** [comment]
I can add an empty extension to `webpacker.yml` and it will fail with:

```
node_modules/@rails/webpacker/node_modules/extract-text-webpack-plugin/dist/lib/helpers.js:15
  return chunk.isInitial() || chunk.parents.length === 0;
               ^

TypeError: chunk.isInitial is not a function
```

**Comment by andrew-aladev** [comment]
It was an issue with misconfigured webpack https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/449

The latest webpack works fine.

**Comment by andrew-aladev** [comment]
It looks like npm don't want to send an exception or something like warning to user when he has invalid fixed version of webpack in `package.json`.

Please add an exception to the `webpacker:verify_install` task to be sure that use don't want to use invalid version of `@rails/webpacker` dependencies.

**Comment by andrew-aladev** [comment]
I can show an detailed example (do not forget to remove both `node_modules` and `package-lock.json` to reproduce it).

Let we have `package.json` with `"webpack": "^3.10.0"`. In this case we will receive single webpack folder in `node_modules`: `node_modules/webpack`.

Let we have `package.json` with `"webpack": "^1.15.0",`. In this case we will receive two webpack folders in `node_modules`: `node_modules/webpack`, `node_modules/@rails/webpacker/node_modules/webpack`

The problem is that `node_modules/.bin/webpack` will be a symlink to the invalid webpack folder.

```
./node_modules/.bin/webpack -> node_modules//webpack/bin/webpack.js
node_modules/@rails/webpacker/node_modules/webpack/.bin/webpack.js -> node_modules/@rails/webpacker/node_modules/webpack/bin/webpack.js
```

But in `lib/webpacker/runner.rb` we can see that we are using webpack from `node_modules` folder.
We can use `node_modules/@rails/webpacker/node_modules` folder here and it will works fine.

But `node_modules/@rails/webpacker/node_modules` won't exist when user's and webpacker's webpack versions are the same. It's a time to say - I hate npm. It is absolutely obvious that npm should postfix each installed binary in `node_modules/.bin/` with it's version.

I don't know a proper way to fix this issue. We can try both `node_modules` and `node_modules/@rails/webpacker/node_modules` in `lib/webpacker/runner.rb`. We can add a special check in `webpacker:verify_install` to verify the version of provided webpack binary.

**Comment by andrew-aladev** [comment]
I've created a feature for npm, but I am sure that they won't fix it in the next few years. We need to find a way to workaround.
