### ISSUE TITLE
Polymer support

### ISSUE THREAD

**Issue by jamesmacwilliam** [rails/webpacker#1040]
I'd like to add support for installing a polymer template similar to what you have for vue/elm/react/angular.  Polymer's setup is a bit more verbose in that it would require:

- programmatically adding 2 script tags when application js is included (a custom elements shim and a webcomponents loader, that are unable to be included in the transpiled file)
- bower installing before webpack:compile.

I'm happy to add a PR for this, if there's interest.

**Comment by gauravtiwari** [comment]
Hey @jamesmacwilliam Thanks for asking but we have only included support for major libraries out there since it's hard to maintain. Also, since we have a simple API, it's really easy to add by yourself. 

**For example:** to add polymer support add this loader: https://github.com/webpack-contrib/polymer-webpack-loader and documentation for adding new loaders is here: https://github.com/rails/webpacker/blob/master/docs/webpack.md#loaders
