### ISSUE TITLE
Webpack executable not found on production

### ISSUE THREAD

**Issue by gauravtiwari** [rails/webpacker#117]
Related to #116. Basically, when using the --production flag, or NODE_ENV=production environment variable, Yarn will not install any package listed in devDependencies. https://yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-production

In our config files we are using packages that also needs to be available on production to compile the assets. Therefore, the dependencies which are used in production should be moved to dependencies block instead of devDependencies. 

I can make a PR once #111 is merged

**Comment by dleavitt** [comment]
Background: right now we're putting build deps under `devDependencies` even though they're required in production.

Pretty sure that setting `NPM_CONFIG_PRODUCTION=false` on production fixes this problem. This should probably be hardcoded into the rake task, in fact.

I think the "correct" solution would be to move everything under `dependencies` rather than `devDependencies`. Right now they're being misused in a way that's convenient (and common) but that doesn't actually reflect their semantics.

**Comment by justin808** [comment]
@dleavitt The only things that should go under devDependencies are things like eslint, flow, the webpack dev server. Any build tools need to be under "dependencies.

**Comment by dleavitt** [comment]
Indeed, that's what I was (trying to) say above. Sure makes package.json prettier when you do it the wrong way though.

**Comment by dhh** [comment]
Yes let's fix the root issue and move away from errant use of devDependencies.

**Comment by elliotjyoung** [comment]
What about Webpack plugins (non babel)? Such as loaders?
