### ISSUE TITLE
Why does this hijack my default webpack bin?

### ISSUE THREAD

**Issue by csergiu** [rails/webpacker#1281]
It's NOT okay to hijack my default webpack command, I have other projects where I'm either not using RoR or they don't use webpacker, and it keeps asking for the config:

> Webpack config /Users/csergiu/[...]/config/webpack/development.js not found, please run 'bundle exec rails webpacker:install' to install webpacker with default configs or add the missing config file for your custom environment.

How do I uninstall this? I don't want to run `node ./node_modules/webpack/bin/webpack.js` everytime. Thanks.

**Comment by gauravtiwari** [comment]
Thanks @csergiu for pointing out. Seems like we accidentally added binstubs as gem executables, will push a PR to fix this. In meantime, you could uninstall the gem - `gem uninstall webpacker`, which will remove executables from path.

**Comment by rossta** [comment]
@gauravtiwari The binstubs are gem executables because that's what was needed to make install work through bundle binstubs. A few potential solutions I could tackle here:

1. Rename the gem's executables so they don't override the npm package, e.g. `webpack` => `webpacker`, `webpacker-dev-server`. We'd keep the convenience of bundle binstubs but also potentially break existing scripts that depend on `bin/webpack` (or provide some symlinks as a mitigating step).
2. Update the executables so they work with bundler, manually copy them during the install step, and remove them from the gemspec so they don't get added to `$PATH`. We'd no longer be able to use bundle binstubs but I'd expect the executables not to change often/ever.

Thoughts?

**Comment by matthewd** [comment]
@rossta I think number two is the way to go; by keeping the class extraction from #833, I agree the generated scripts should ~never need to change.

**Comment by gauravtiwari** [comment]
Thanks @rossta 🍰 

As @matthewd pointed out number 2 makes more sense.

**Comment by csergiu** [comment]
THIS IS STILL AN ISSUE WITH THE LATEST VERSION!!!!!!1
