### ISSUE TITLE
manifest.json doesn't include relative_url_root.

### ISSUE THREAD

**Issue by jpickwell** [rails/webpacker#1357]
For production sandbox deployment I have the app "mounted" under a subdirectory; e.g., `example.com/subdir`.

Currently, webpacker doesn't include the `RAILS_RELATIVE_URL_ROOT` in the `manifest.json`, even if it's set.

**Comment by sspread** [comment]
@gauravtiwari @jpickwell Is this right? I'm also 'mounting' my app under a subdirectory, but it only works if I remove the code merged here. I believe the `manifest.json` should not include `RAILS_RELATIVE_URL_ROOT` as part of the asset paths.

**Comment by jpickwell** [comment]
This worked for the app I was working on at the time, but a lot has changed. That app is now on a dedicated subdomain, so I'm no longer using `RAILS_RELATIVE_URL_ROOT`. There have been changes to how `publicPath` is calculated, so this may need to be revisited.

**Comment by rodrigomanhaes** [comment]
@sspread the removal of relative path broke all urls inside scss files in my app when it runs in a subdirectory. Generated URLs don't include the app subdirectory in `RAILS_RELATIVE_URL_ROOT`. All works fine except urls references inside sass files, including ones from packages (e.g. font awesome).

**Comment by rdavid369** [comment]
@sspread - What was the underlying problem that caused this to be removed?  We deploy quite a few apps in sub directories and currently, webpack doesn't seem to know anything about the relative url root, so assets within assets, like images used as background images for DOM elements, do not properly resolve because they are missing the relative url root.
