### ISSUE TITLE
getting a 404 for /javascript/packs/application.js 

### ISSUE THREAD

**Issue by killercarwash** [rails/webpacker#1390]
Hi, 

I'm kinda new to rails and I've been struggling with this problem for last 2 days and nothing seems to be working. The problem is ```console.log('Hello World from Webpacker')``` won't show up in the console instead I get this: 

GET http://localhost:3000/javascript/packs/application.js 404 (Not Found)

 I've put  
``` <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %> ```

in my application.html.erb and ive install then reinstalled webpacker and nothing seems to be working.

Thanks. 

Edit: 

Whoops looks like I didn't add ``` <%= javascript_pack_tag 'application' %>```  in  application.html.erb
I can't believe it took me 2 days to figure this out. 

Strangly Hello world from webacker is shwoing the console now but im still getting  ```GET http://localhost:3000/javascript/packs/application.js``` in the console ?

**Comment by killercarwash** [comment]
![image](https://user-images.githubusercontent.com/32937174/38089421-4baa176a-3357-11e8-8d28-2336063e469e.png)

It showing the console.log  "Hello World from Webpacker" as you can see but I'm still getting the 404(NOT found) ???

**Comment by amrabt** [comment]
p

Le jeu. 29 mars 2018 à 14:45, Connor Ingold <notifications@github.com> a
écrit :

**Comment by rossta** [comment]
@killercarwash What version of rails, `webpacker` gem , and the `@rails/webpacker` npm package are you using? What is in your `config/webpacker.yml` file?

By default, I'd expect the url of your application.js file to be something like ` http://localhost:3000/packs/application-3f225177efeb4e965518.js`, (no `javascript/` path part, has a fingerprint), so, if you are on past versions of those dependencies, you may benefit from upgrading, otherwise we can try to see if something is up with your configuration

**Comment by killercarwash** [comment]
Hi, 

Somebody just helped me solve it. I was loading the javascript before the HMTL. 

Thanks for the reply anyway :+1:
