### ISSUE TITLE
Incorrect/confusing docs regarding NODE_ENV

### ISSUE THREAD

**Issue by RKushnir** [rails/webpacker#1406]
I'm using webpacker **3.4.1**.

There's this text in the readme:
> Webpacker will use *production* environment as a fallback environment for loading configurations

and

>For example, the below command will compile assets in *production* mode but will use staging configurations from config/webpacker.yml if available or use fallback *production* environment configuration:
```bash
RAILS_ENV=staging bundle exec rails assets:precompile
```
and
```bash
# compiles in production mode by default unless NODE_ENV is specified
bundle exec rails assets:precompile
```

Which doesn't seem to be true for me, as when I run this command it uses the development settings.
This behavior has probably been changed by https://github.com/rails/webpacker/commit/e61618465f872694775d1a39c10cf55d9df939ea.

Weird is that the above paragraphs have been added to the readme(https://github.com/rails/webpacker/commit/d418bcff71a920b6e3e9968dbb863751fc329e13#diff-04c6e90faac2675aa89e2176d2eec7d8) 12 days ago, which was after the code change(15 days ago).

And then in the readme there's another contradicting paragraph:
> ## Deployment
> Webpacker hooks up a new webpacker:compile task to assets:precompile, which gets run whenever you run assets:precompile. If you are not using Sprockets, webpacker:compile is automatically aliased to assets:precompile. *Remember to set NODE_ENV environment variable to production during deployment or when running this rake task.*

So what is the expected behavior and which part of the readme is correct?

/cc @gauravtiwari

**Comment by gauravtiwari** [comment]
> Which doesn't seem to be true for me, as when I run this command it uses the development settings.
This behavior has probably been changed by e616184.

Do you have staging configuration inside config/webpacker.yml?

> Weird is that the above paragraphs have been added to the readme(d418bcf#diff-04c6e90faac2675aa89e2176d2eec7d8) 12 days ago, which was after the code change(15 days ago).

The README was updated when a new release was made, not when that PR was merged. 

----

Here is a screenshot of how it works: 

1. First time there is no configuration in webpacker.yml so production is used for both:

<img width="982" alt="screen shot 2018-04-04 at 10 25 23" src="https://user-images.githubusercontent.com/771039/38299637-86f98bbc-37f2-11e8-8043-bd054e2a0bed.png">

*Please read logs*

2. Staging configuration is available and packs are compiled in packs-staging. 

> Deployment

Yeah, the deployment docs need updating since rake task always sets `NODE_ENV` to production, same as sprockets.

**Comment by gauravtiwari** [comment]
As a side note, please ensure both gem and npm package is updated to 3.4.1 or 3.4.3 (latest)

**Comment by RKushnir** [comment]
Thanks for the quick response.

I suspect the confusion may be between what is meant by "production environment". `RAILS_ENV` is indeed set to "production", but `NODE_ENV` is set to "development" by default, unless I specify it explicitly in the command.

To answer your question, I don't have a staging env in the webpacker(and at all), and I tried both with `RAILS_ENV=staging` and without `RAILS_ENV`.

Also, I was using the 3.4.1 version of the npm package, but updating to 3.4.3 didn't make a change.

**Comment by gauravtiwari** [comment]
> NODE_ENV is set to "development" by default, unless I specify it explicitly in the command.

Nope, if you are running the rake task. If you are running `./bin/webpack` in development then NODE_ENV will be development. 

What is your use case?

**Comment by RKushnir** [comment]
In the script to build a docker container for deployment, I'm running `RAILS_ENV=production bundle exec rake assets:precompile`.
I just started using webpacker and noticed that the deployed JS file was built for development(uncompressed and with source maps).

**Comment by RKushnir** [comment]
As a workaround, I edited `bin/webpack` this way:
```ruby
ENV["NODE_ENV"]  ||= ENV["RAILS_ENV"] == "development" ? "development" : "production"
```

**Comment by gauravtiwari** [comment]
That's strange because I just compiled it and the packs are compressed and with proper sourcemaps so I would double check if the versions are definitely up to date. So it should compile in production mode even without settings RAILS_ENV: `bundle exec rake assets:precompile`

Also, you might wanna run `bundle exec rails webpacker:install` (if old project)

**Comment by RKushnir** [comment]
I tried creating a new dummy app and was able to figure out that when using a `react_on_rails`, either the gem by default or the way we use it causes `NODE_ENV` to fallback to "development". So I'm going to close this issue.

Sorry for the false alert and thank you for your help. 🍻

**Comment by gauravtiwari** [comment]
@RKushnir Ahh I see, `react_on_rails` has it's precompile task.
