### ISSUE TITLE
vue-loader v15 requires VueLoaderPlugin in webpack config

### ISSUE THREAD

**Issue by rlafranchi** [rails/webpacker#1453]
details: https://vue-loader.vuejs.org/migrating.html#migrating-from-v14

cc @ytbryan

**Comment by ytbryan** [comment]
For anyone reading, the temporary solution is to downgrade to v14.2.2
 
Run: 

`yarn upgrade vue-loader@14.2.2`

@rlafranchi thanks for reporting!

**Comment by bbugh** [comment]
A better temporary solution since `vue-loader` v15 fixes a bunch of bugs including the [css-out-of-order in production bug](https://github.com/vuejs/vue-loader/issues/808) is to add to environment.js

```javascript
// environment.js

// Required for vue-loader v15
const VueLoaderPlugin = require('vue-loader/lib/plugin')
environment.plugins.append(
  'VueLoaderPlugin',
  new VueLoaderPlugin()
)

module.exports = environment
```

**Comment by gauravtiwari** [comment]
What's the permanent solution? 😄 Did we fix this in 4.x?

**Comment by ytbryan** [comment]
Yup, it's fixed in 4.x but the user has  to choose the latest vue-loader at `rails webpacker:install:vue`. 
![screenshot 2018-10-06 11 54 41](https://user-images.githubusercontent.com/323891/46567120-719d2400-c95f-11e8-8f61-7b383598c687.png)

**Comment by msencenb** [comment]
@bbugh solution seems to mostly work for me, although I also had to append a new rule into the webpack config that targets vue. But... that custom loader seems like it results in my vue components not respecting my .babelrc plugin of 'transform-class-properties', which causes my app to break on IE11 because of arrow functions. Not sure yet what to do about that. 

```
// Necesary configuration for vue-loader v15
const VueLoaderPlugin = require('vue-loader/lib/plugin');
environment.plugins.append(
    'VueLoaderPlugin',
    new VueLoaderPlugin()
);
environment.loaders.append('vue', {
    test: /\.vue$/,
    loader: 'vue-loader'
});
```

**Comment by gauravtiwari** [comment]
Please try the latest RC, otherwise feel free to open a new issue with more details.

**Comment by afuno** [comment]
Write this in the console:

```
yarn upgrade vue-loader@last
```

Next, choose version 14.2.3. Not 15 version, within the 14 version. In my case, this corrected the situation.

**Comment by MelMacaluso** [comment]
For anyone going crazy about matching thirty-thousand different front-end versions in order to avoid some random undocumented compatibilities on a nightly-bleeding-edge new release of a peerDependency that you had to randomly install on a blue moon in 1834, it needs the following in your webpack.config.js

```
const VueLoaderPlugin = require('vue-loader/lib/plugin')
...
plugins: [
  new VueLoaderPlugin()
]
```

**Comment by reiz** [comment]
With webpack 5.49.0 and vue-loader 16.5.0 it doesn't work anymore. Now getting this message: 

```
TypeError: VueLoaderPlugin is not a constructor
```

In the webpack config I'm loading it like this: 

```
const VueLoaderPlugin = require('vue-loader/dist/pluginWebpack5');
```

And in the Plugins area I'm calling `new VueLoaderPlugin()`. But it doesn't work!

**Comment by reiz** [comment]
I just figured it out. It has to be imported like this: 

```
const { VueLoaderPlugin } = require('vue-loader')
```

Then it works!
