### ISSUE TITLE
webpacker:install fails -> ArgumentError: Malformed version number string Yarn v0.1.1 2011 Jesper Kjeldgaard

### ISSUE THREAD

**Issue by stevenmaguire** [rails/webpacker#1461]
When including the webpacker gem and the yarn gem, I am encountering an issue...

```shell
# console
$ bin/rails webpacker:install
rails aborted!
ArgumentError: Malformed version number string Yarn v0.1.1 2011 Jesper Kjeldgaard
/path/to/project/bin/rails:9:in `<top (required)>'
/path/to/project/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => webpacker:install => webpacker:check_yarn
(See full trace by running task with --trace)
```

```ruby
# Gemfile.rb
ruby '2.5.1'
gem 'rails', '~> 5.2.0'
gem 'webpacker', '~> 3.4'
gem 'yarn'
```

Is this an issue with webpacker gem, yarn gem, and/or rails? Any clues well appreciated. Thanks!

**Comment by renchap** [comment]
The `yarn` used by Webpacker is not the gem, its https://yarnpkg.com/en/ a dependency management tool for Javascript.

You should uninstall the `yarn` gem, and install the JS `yarn`: https://yarnpkg.com/en/docs/install

**Comment by stevenmaguire** [comment]
I had to manually remove that binary. It now proceeds. Odd.

**Comment by bearpatrol64** [comment]
THANKS!! THAT SAVED MY SANITY
I couldn't find the answer anywhere.

**Comment by EarlyZhao** [comment]
This problem is funny. 

The gem webpacker will check if the yarn was installed. [check code](https://github.com/rails/webpacker/blob/227661b546701e107213aa9b6f83451bc89cf7d5/lib/tasks/webpacker/check_yarn.rake). The yarn that webpacker want to check is JS yarn, install by https://yarnpkg.com/en/docs/install.

But if you add the gem 'yarn' in your Gemfile, there will be a binary named yarn installed after bundle install. The gem yarn's binary has the same name of JS yarn. When the [check code](https://github.com/rails/webpacker/blob/227661b546701e107213aa9b6f83451bc89cf7d5/lib/tasks/webpacker/check_yarn.rake#L5) execute, it may find the  gem yarn's binary first in the .RVM path, which is wrong binary for webpacker.

So, find the binary named 'yarn' in all the .RVM path, then remove all of them.
