### ISSUE TITLE
javascript is not load in Production 

### ISSUE THREAD

**Issue by yongwoon** [rails/webpacker#1520]
### My project work well in local env.
![2018-05-24 15 54 21](https://user-images.githubusercontent.com/9317029/40469335-2ac01ece-5f6b-11e8-8510-46804ff648a3.png)

### But, When I deploy the app to ec2 via capistrano 3, Vue js does not work. And also no error message?

![2018-05-24 16 01 12](https://user-images.githubusercontent.com/9317029/40469539-d9f2057e-5f6b-11e8-904e-aa7be6f74518.png)

What's problem ?

## Project Env
```
Rails 5.2
webpacker verson: 3.5
vue version: 2.5.16
vue-loader 14.2.2
vue-template-compiler 2.5.16
```
## package.json
```
{
  "name": "dream_line",
  "private": true,
  "dependencies": {
    "@rails/webpacker": "3.5",
    "vue": "^2.5.16",
    "vue-loader": "14.2.2",
    "vue-template-compiler": "^2.5.16"
  },
  "devDependencies": {
    "webpack-dev-server": "2.11.2"
  }
}
```

# environments/production.rb
```
Rails.application.configure do
  config.webpacker.check_yarn_integrity = false
  config.cache_classes = true
  config.eager_load = true
  config.consider_all_requests_local       = false
  config.action_controller.perform_caching = false
  config.public_file_server.enabled = ENV['RAILS_SERVE_STATIC_FILES'].present?
  config.assets.js_compressor = :uglifier
  config.assets.css_compressor = :sass
  config.assets.compile = false
  config.active_storage.service = :local
  config.log_level = :debug
  config.log_tags = [ :request_id ]
  config.i18n.fallbacks = true
  config.active_support.deprecation = :notify
  config.log_formatter = ::Logger::Formatter.new

  if ENV["RAILS_LOG_TO_STDOUT"].present?
    logger           = ActiveSupport::Logger.new(STDOUT)
    logger.formatter = config.log_formatter
    config.logger    = ActiveSupport::TaggedLogging.new(logger)
  end
  config.active_record.dump_schema_after_migration = false
end
```

# config/webpack/production.js
```
process.env.NODE_ENV = process.env.NODE_ENV || 'production'

const environment = require('./environment')

module.exports = environment.toWebpackConfig()

```

**Comment by gurkanoluc** [comment]
I'm having the same issue.

**Comment by xlanex6** [comment]
So I am...

**Comment by xlanex6** [comment]
@yongwoon / @gurkanoluc Do you find a solution ? I'm still on it

**Comment by gauravtiwari** [comment]
Could you please share an example on github?

**Comment by feliperaul** [comment]
Same issue here as well.

**Comment by feliperaul** [comment]
@gauravtiwari Take a lok at a real world, production example:

https://planilha.tramitacaointeligente.com.br/planilhas/ED2sUXz32-R9CJKdkmtf8Q

If you want to see the code of this example, I posted it on SO: https://stackoverflow.com/questions/50957238/vue-js-app-works-in-development-but-not-mounting-template-in-production-with-rai

**Comment by torce** [comment]
Same issue here.
I have tried with several browsers.  happens with chromium 57, Chrome 67 but surprisingly works with Firefox ESR 52.
When I select the element `<!-- -->` and reload the page, I can see in the inspector for a moment the `<div>` of the vue element, then disappears.

**Comment by feliperaul** [comment]
@torce I managed to finally fix it changing the way of mounting the component.

Try `import Vue from 'vue'` (instead of `vue/dist/vue.esm`) and then:

```
const app = new Vue({
    el: domElement,
    render: h => h(RootComponent)
  })
```

The comments that appear in the hello_vue.js scaffold tell you that you can choose between using the DOM as your template OR loading the component with a render function; they both do work in development, but only the latter (loading the component with a render function, using `vue` instead of `vue/dist/vue.esm` and `render: h => h(RootComponent)` worked for me in production.

This has been, by far, the longest, most frustrating debugging session of my life.

Source of solution: https://stackoverflow.com/a/48651338/1290457

**Comment by torce** [comment]
I solved it finally, I still don't know exactly what happened, but it seems related with vue-router.
I was deploying to a subpath in the server (`mydomain.com/testing`) and using the history mode of vue-router. Things that I have tried:

- Changing the history mode to the default one solved it.
- Changing the deployment path to the root of the domain worked also.
- Setting the base parameter of vue-router as suggested [here](https://stackoverflow.com/questions/47622452/blank-page-with-vue-router-with-history-mode-and-production) didn't work.

It still surprises me that this doesn't show any error or warning in the console. I don't know if the problem is related with vuejs, vue-router, webpacker or if this is the intended behaviour.

**Comment by howtwizer** [comment]
In case of Vue.js and production problems.
In my case problem was in content security policy recommendations from webpacker docs. 

```
Rails.application.config.content_security_policy do |policy|
  if Rails.env.development?
    policy.script_src :self, :https, :unsafe_eval
  else
    policy.script_src :self, :https
  end
end
```

Removing `else` part fixing production.

Chrome silently ignoring this. Firefox shows warnings.

**Comment by jits** [comment]
Just to add to @howtwizer's suggestion above, which solved the issue for us:

We use FirebaseUI, which needs the ability to load third party scripts. Thus removing the CSP rule solved the issue in a non-development environment.
