### ISSUE TITLE
Upgrade guide from 3.x.x to 4.x.x

### ISSUE THREAD

**Issue by humphreybc** [rails/webpacker#1531]
Hi, I am trying to upgrade our project from 3.x.x to 4.x.x and I'm having a lot of difficulty. Is there a step-by-step upgrade guide I can follow somewhere? What state is the 4.x.x release in?

I've tried simply blowing away our old configuration and running `bundle exec rails webpacker:install` but that doesn't work. I've run into https://github.com/rails/webpacker/issues/1295 and https://github.com/rails/webpacker/issues/1500 along with `Cannot find module 'webpack/schemas/WebpackOptions.json'` at various times while trying to upgrade to 4.x.x.

Some more information on what's required to migrate to 4.x.x would be great.

**Comment by gauravtiwari** [comment]
Thanks, @humphreybc The current 4.x release is a pre-release and there is some work still left to be done including documentation. We are working on this and hopefully should have a stable release in next 2 weeks. 

But if you want to upgrade now, what happens if you follow these steps in your app:

```
yarn add @rails/webpacker@4.0.0-pre.2
yarn add webpack-cli
```

add 4.x version to gemfile and run `bundle update`

then run: `bundle exec rails webpacker:install` (please check diff before replacing existing files)

**Comment by vcavallo** [comment]
As @humphreybc said, _do not_ run the install script if you're doing a delicate and complicated upgrade. 

I finally got my setup working with `webpack-dev-server`, Vue.js, Rails and Webpacker _served over nginx running on a remote dev vps_.  I ssh in to a vps to do dev work and getting webpacker and the webpack dev server working there was ... fun!

This gist is sort of a mess because it was never intended for sharing, but maybe it might help someone else in a similar situation: https://gist.github.com/vcavallo/22cac63d01e3b73a56a92a619c6ff698

**Comment by shelmire** [comment]
I also had some trouble with the upgrade process.

I did:

```
yarn add @rails/webpacker@4.0.0-pre.2
yarn add webpack-cli
```
Add gem 'webpacker', '>= 4.0.x' to Gemfile. Then,
```
bundle install
```

The trouble was with `bundle exec rails webpacker:install`

**Comment by dreyks** [comment]
@gauravtiwari is there a roadmap to stable 4?

**Comment by gauravtiwari** [comment]
Just made another pre-release (with babel 7 support):

```
yarn add @rails/webpacker@next
bundle update webpacker
```

I will put the milestone in an issue. Mainly, I need to go through all the issues and merge engine support PR.

**Comment by gauravtiwari** [comment]
Please use the latest RC, and feel free to open a new issue with more details if this is still an issue.
