### ISSUE TITLE
Rails 5.2, webpacker 3.5.3, react projects and puma-dev (0.11)

### ISSUE THREAD

**Issue by resistorsoftware** [rails/webpacker#1533]
I am not understanding the security issues here after hours of abuse. 
My puma-dev config dishes out a rails App without difficulty. However, webpacker also dishes out the assets via a separate process. My console is filled with errors and security issues. 

__HOW DO DEVELOPERS WITH EXPERIENCE DO IT?__

My webpacker.yml is set to a puma-dev port that I called fizzbuzz.test (and I tried leaving it as .dev and tried .localhost), with https true.

    dev_server:
        https: true
        host: fizzbuzz.test
        port: 3032
        public: fizzbuzz.test:3032

I also set the CSP Policy for this domain:

    Rails.application.config.content_security_policy do |policy|
      policy.connect_src :self, :https, "https://fizzbuzz.test:3032", "wss://fizzbuzz.test:3032" if Rails.env.development?
    end

In the end, my App boots, and serves, but the console fills with errors on certificate names, and no WSS or XHR calls work for the assets. I tried approving the __localhost__ certificate issued but that did not help. Why is a domain like fizzbuzz.test covered by a localhost certificate anyway?

If Puma-Dev is the problem, please tell me what I should be using instead. This is terribly defeating as not having things work in dev gives me zero confidence this will work production wise.

**Comment by gauravtiwari** [comment]
@resistorsoftware What happens if you change dev server config to: 

```
dev_server:
    https: true
    host: localhost
    port: 3032
    public: localhost:3032
```

dev server can only bind to `localhost` `0.0.0.0` or `127.0.0.1` (https://webpack.js.org/configuration/dev-server/#devserver-host) so it seems that dev server isn't running at all. What output do you get in your terminal when running dev server alone?

There is a dev server middleware that proxies requests from rails app to webpack dev server so you don't need to setup special domains for it, just use default settings however your rails app can use custom domains.

**Comment by resistorsoftware** [comment]
It turns out that that is the way to go. When I followed the link to the URI issued by the dev-server and I saved the invalid certificate issued, I was then able to get that certificate approved for system use, and all of a sudden https: and wss: problems went away.

That being said, it is a bad developer experience when using Puma-Dev that this certificate issue comes up with every new project. Would be swell to have one localhost certificate that always just worked.
