### ISSUE TITLE
Simply depending on @rails/webpacker isn't enough? Possibly need to add all dependencies to package.json

### ISSUE THREAD

**Issue by swrobel** [rails/webpacker#1537]
I've had a very confusing conversation with the yarn team on [this issue](https://github.com/yarnpkg/yarn/issues/5749#issuecomment-393140599) which has led them to indicate that all dependencies that are directly used by a project need to be in package.json, they can't simply be implied by being dependencies of another package in package.json. This particular issue caused `babel-loader` to not be available to my app after using `yarn upgrade`.

**Comment by rmehner** [comment]
I've ran into the same thing and did a quick check with npm (`5.7.1`, not the current one) instead of yarn and there everything worked. But once I use yarn (`1.7.0`) and upgrade webpacker from `3.2.2` to `3.4.1` (while following the steps described in the README to upgrade), compilation will always fail with `ERROR in Entry module not found: Error: Can't resolve 'babel-loader'`. Going back to webpacker 3.2.2 everything still works, even with Yarn.

As I'm a bit short on time right now, I didn't investigate further and simply pinned everything to 3.2.2, but something seems to have changed between those versions that Yarn doesn't like. But that's just a hunch :)

**Comment by swrobel** [comment]
Not sure why this was closed @jakeNiemiec. Yarn is moving towards the PnP system that explicitly prevents accessing dependencies of another package, see https://yarnpkg.com/en/docs/pnp/troubleshooting

**Comment by jakeNiemiec** [comment]
> Yarn is moving towards the PnP system that explicitly prevents accessing dependencies of another package

@swrobel [See the Yarn Plug’n’Play ticket](https://github.com/rails/webpacker/issues/2112). We can focus there on eliminating the reliance on cross package boundaries in this file:

https://github.com/rails/webpacker/blob/848161489864b247ade97ddb4da9302a79eda3c0/lib/install/template.rb#L37-L46

Additionally, webpacker was a very different tool back when this was posted. There have been updates to both the webpacker and node.js sides of the problem. If you want to keep this open, could you post updated info about what packages are still missing in `package.json`?
