### ISSUE TITLE
DevDependencies vs Dependencies

### ISSUE THREAD

**Issue by artemgurzhii** [rails/webpacker#160]
Current behaviour
```json
"dependencies": {
    "babel-core": "^6.23.1",
    "babel-preset-env": "^1.2.0",
    "coffee-loader": "^0.7.3",
    "coffee-script": "^1.12.4",
    "compression-webpack-plugin": "^0.3.2",
    "glob": "^7.1.1",
    "path-complete-extname": "^0.1.0",
    "rails-erb-loader": "^3.2.0",
    "webpack": "^2.2.1",
    "webpack-merge": "^3.0.0"
  }
```

expected
```json
"devDependencies": {
    "babel-core": "^6.23.1",
    "babel-preset-env": "^1.2.0",
    "coffee-loader": "^0.7.3",
    "coffee-script": "^1.12.4",
    "compression-webpack-plugin": "^0.3.2",
    "glob": "^7.1.1",
    "path-complete-extname": "^0.1.0",
    "rails-erb-loader": "^3.2.0",
    "webpack": "^2.2.1",
    "webpack-merge": "^3.0.0"
  }
```

Installed via yarn packages should be added to the `devDependencies` as they used only in development.

**Comment by artemgurzhii** [comment]
Should I create pull request for this?

**Comment by gauravtiwari** [comment]
Hey @artemgurzhii, please checkout this issue - https://github.com/rails/webpacker/issues/117, it's discussed here. Feel free to close the issue, if that answers your question :)

**Comment by artemgurzhii** [comment]
What about this?
```ruby
if ENV['NODE_ENV'] == 'production'
  run './bin/yarn add webpack webpack-merge path-complete-extname babel-loader babel-core babel-preset-env coffee-loader coffee-script compression-webpack-plugin rails-erb-loader glob'
  run './bin/yarn add --dev webpack-dev-server'
else
  run './bin/yarn add --dev webpack webpack-merge path-complete-extname babel-loader babel-core babel-preset-env coffee-loader coffee-script compression-webpack-plugin rails-erb-loader glob webpack-dev-server'
```

**Comment by gauravtiwari** [comment]
@artemgurzhii This installer is run only once, when you add webpacker using `webpacker:install`. Obviously, you can do that, but it's not something that will work,

1. You will have to install webpacker in production in all your deploys, manually (for container-based)
2. Your package.json will go out-of-sync, say if you are using Git. You commit something and then production installs something differently, resulting in conflicts. 
3. Number#2 will then introduce version differences because you got two package.json, technically

btw, what are your concerns on this? If you look at the webpack config files, you will see the dependencies that are being installed as `primary` are used in same way in both the environments so,  that means they are dependencies of the app as whole - whether it's a build tool or plugins used by build tool.

**Comment by artemgurzhii** [comment]
@gauravtiwari Haven't thought about that, thanks for explaining)
