### ISSUE TITLE
Assets can't be load

### ISSUE THREAD

**Issue by rezadhah** [rails/webpacker#1630]
Currently i structure my webpacker related folder like this
```
app/
   javascript/
     components/
     containers/
     images/
     packs/
     styles/
     utils/
```

the problem is, i cant access my assets in **styles** directory like `<%= stylesheet_pack_tag 'styles/admin/first.css' %>`

did i do something wrong?

**Comment by ace-subido** [comment]
> styles/admin/first.css

Hi @rezadhah, did you have an javascript entry file (inside `javascript/packs`) that imported this CSS file?

**Comment by rubendinho** [comment]
Here's how I have this organized, if it's helpful:

I have my styles in `app/javascript/application/styles/index.scss`. Then I import these styles and relevant JS components in an `index.js` manifest, and then I import that manifest in an `application.js` pack file.    

```
# app/javascript/application/index.js
import './styles/';
...
```

```
# app/javascript/packs/application.js
import 'application'
```

```
# app/views/layouts/application.html.erb
...
<%= stylesheet_pack_tag 'application' %>
<%= javascript_pack_tag 'application' %>
...
```

**Comment by rezadhah** [comment]
@ace-subido no, i still have the default code from webpacker in packs/application.js.
still kind of struggle to make my own folder inside app/javascript can be compiled by webpack ..

**Comment by rezadhah** [comment]
@rubendinho interesting, but it's not so dynamic imho. can i get my assets inside app/javascript all compiled by webpack without import them inside application.js?

**Comment by rubendinho** [comment]
@rezadhah I would organize all your assets inside `application.js` and then import the pack once into application.html.erb.  I found this approach to make for an easier transition from the asset pipeline.

**Comment by ace-subido** [comment]
> @ace-subido no, i still have the default code from webpacker in packs/application.js.
still kind of struggle to make my own folder inside app/javascript can be compiled by webpack ..

Ah, I see, you need to import that `import './styles/';` inside the `packs/application.js`. Just like how @rubendinho 's example.

> can i get my assets inside app/javascript all compiled by webpack without import them inside application.js

Webpack needs a javascript entry file inside `packs`, it's the convention of that bundler. This is because webpack uses `loaders` to bundle images/css/fonts inside your entry file. To check out how it works in practical examples, you can view this guide: https://webpack.js.org/guides/asset-management/. 

- Webpack compiles the imports (CSS, images, etc.) to a javascript entry file, then that needs to be included inside a view via `javascript_pack_tag`.
- After including it in the view, then you can use the stylesheets imported in that javascript file `stylesheet_pack_tag`.

Out of the box, it doesn't behave like the sprockets asset pipeline, where CSS/SCSS/Image/Font files get separately compiled and then you can directly access it in the views. You'll have to configure it in order for you to achieve the old `sprockets-like` behavior. (i.e. using `copy-webpack-plugin`, etc.)

**Comment by rezadhah** [comment]
thank you for your kind help @ace-subido @rubendinho :D
