### ISSUE TITLE
stylesheet_pack_tag not outputting a <link> tag in stage environment

### ISSUE THREAD

**Issue by njgingrich** [rails/webpacker#1659]
Everything works as expected in development - CSS loads with HMR. But in our stage environment, there is no `<link>` tag produced inside the `<head>`, so no styles are displayed. The CSS is bundled and is inside the `manifest.json`, and if I include the tag manually myself it is imported, but it is not automatically generated.

I have two packfiles: `application.js` and `vendor.js`

`packs/application.js`:
```

import ReactRailsUJS from 'react_ujs'
import '../src/javascript/application'
import '../src/stylesheets/application.scss'


// Support component names relative to this directory:
const componentRequireContext = require.context('src/javascript/components', true)
ReactRailsUJS.useContext(componentRequireContext)
```

`packs/vendor.js`
```
import 'alertifyjs'
import $ from 'jquery'
import Rails from 'rails-ujs'
import Turbolinks from 'turbolinks'

import '../src/javascript/vendor/...'

Rails.start()
Turbolinks.start()
window.$ = $
```

`config/webpack/environment.js`
```
const { environment } = require('@rails/webpacker')
const webpack = require('webpack')

// Add an ProvidePlugin
environment.plugins.prepend(
  'Provide',
  new webpack.ProvidePlugin({
    $: 'jquery',
    ...
  }),
)

environment.plugins.append(
  'CommonsChunk',
  new webpack.optimize.CommonsChunkPlugin({
    name: 'vendor',
    chunks: ['vendor', 'application'],
    minChunks(module) {
      return module.context && module.context.indexOf('node_modules') >= 0
    },
  }),
)

module.exports = environment
```

`layouts/_head.slim`
```
head
  ...
  = javascript_pack_tag 'vendor'
  = stylesheet_pack_tag 'application'
  = javascript_pack_tag 'application'
  ...
```

`manifest.json`
```
{
  "application.css": "/packs/application-a8c61543b9808cdd6b94e6544d65762d.css",
  "application.js": "/packs/application-912a6bfaa4e74607113f.js",
  "application.js.map": "/packs/application-912a6bfaa4e74607113f.js.map",
  "vendor.js": "/packs/vendor-b0ebf7263c1bbd80e607.js",
  "vendor.js.map": "/packs/vendor-b0ebf7263c1bbd80e607.js.map"
}
```

Outputted HTML:
```
<head>
  <script src="/packs/vendor-b0ebf7263c1bbd80e607.js"></script>
  <script src="/packs/application-912a6bfaa4e74607113f.js"></script>
</head>
```

**Comment by bitterloa** [comment]
same here, in development my pack css is loaded but in staging/production the whole <link> stylesheet tag is completely absent. did you ever figure out what was going on?

**Comment by leouofa** [comment]
> same here, in development my pack css is loaded but in staging/production the whole stylesheet tag is completely absent. did you ever figure out what was going on?

Having the same issue here. Any ideas?

**Comment by leouofa** [comment]
It's happening in development. It actually works fine in production.

**Comment by leouofa** [comment]
Figured it out. The Gemfile didn't specify webpacker version.

**Comment by bitterloa** [comment]
> Having the same issue here. Any ideas?

@leouofa no I never figure this out. To be honest I'm kind of frustrated with the whole webpack hype-train and find Sprockets to be much more reliable, easier to understand, and *faster* to compile while developing than webpack. So for now I've abandoned trying to use a javascript compiler like webpack to create my stylesheets and I'm using the good ol' Rails asset pipeline/Sprockets instead (and much happier). However not sure how long this will be feasible after I begin developing more Vue.js components? But for now it's working. I'm using the latest pre-release branch of the webpacker gem because i want to use webpack 4 instead of 3:

`gem 'webpacker', '>= 4.0.x'`

**Comment by jakeNiemiec** [comment]
> @bitterloa To be honest I'm kind of frustrated with the whole webpack hype-train and find Sprockets to be much more reliable, easier to understand, and faster to compile while developing than webpack. 

I wouldn't judge`webpack` by how `webpackER` implements it. `webpackER` tries to cater to every single JS framework and breaks conventions along the way.

My suggestion? Just use `webpack` without a rails wrapper (like it was intended to be used). That way, when you get to `Vue.js`, you can just [follow the `Vue.js` docs as they are written](https://vue-loader.vuejs.org/guide/#manual-configuration) without having to translate `webpack` directions into `webpackER` directions. If you stick with `webpackER` + `Vue.js`, this repo has a bunch of [good issues](https://github.com/rails/webpacker/issues/1520#issuecomment-399112369) discussing how to get `Vue.js` configured just right. Best of luck!

**Comment by bitterloa** [comment]
hi @jakeNiemiec, thanks for the tip :-) however in this case i'm not judging webpack by webpackER although this bug is isolated to the webpackER gem -- I have a separate project using webpack + Angular, and honestly it's been a huge pain and time-sink just trying to get the project to compile. I spend as much time getting webpack to work as I do developing the front-end. I'm doing a newer project in Vue.js because it looks much lighter than Angular and just awesome all around, but I'm staying away from any single-page app type setups just to not have to deal with the headache. I had to upgrade my other project from Webpack 2 / Angular 5 to Webpack 4/Angular 7 and it was a complete *nightmare*! I lost a ton of hours and can't really justify charging my client for the weeks worth of time to figure it out. 

In general, this is one of the most difficult times for javascript development so i just want to simplify things as much as possible. And at least on my setup, webpack was way slower to compile compared to Sprockets--i'm sure there's tons of 'options' to tweak in webpack to try and get it to work better but this is exactly what i don't want to have to worry about. I'm super stoked about Vue.js though...I'm kind of over Angular at this point since it left a bad taste in my mouth last year (it's a much larger framework and the 'official' build system isn't even being used anymore by programmers). I've been using webpack since v1 and it's still too problematic in my opinion...but what other options are there nowadays? So, if I can, I think i'm gonna try and start a revolution to use Sprockets if at all possible :-) we'll see how it goes!

**Comment by jakeNiemiec** [comment]
>  I had to upgrade my other project from Webpack 2 / Angular 5 to Webpack 4/Angular 7 and it was a complete nightmare! I lost a ton of hours and can't really justify charging my client for the weeks worth of time to figure it out.

Been there done that. `Vue.js` takes the best ideas form `Angular` (and some from `React`), without putting you in ZoneAwareError hell.

> but what other options are there nowadays?

https://parceljs.org/ and https://rollupjs.org work pretty well as alternatives You would need to find or create a `webpack-assets-manifest` alternative and implement the webpackER `lookup!` functionality in order to get Rails to load certain modules (this is why I still love webpack). I've been meaning to write a tech article on how to connect Rails with an arbitrary package manager, but everyone uses Rails differently with different expectations.

**Comment by bitterloa** [comment]
hey ParcelJs and RollupJs look sweet! Thanks, this is like a light at the end of the tunnel for me. Will check them out for sure. 

It seems to me like it wouldn't be too difficult to substitute any js build system and use with Rails since you'd just need to include a link to the bundled js and css files in the main application.html.erb layout file and go from there. But this is my limited experience. I've been trying out webpackER just to make sure i stay on top of the latest "Rails way" of doing things but most of my grumbles/gripes come from using webpack in general. I mean what webpack does is awesome and necessary I suppose, but i wonder for a lot of projects...I still have a hard time understanding what webpack does better than Sprockets since both of them take a bunch of js files and bundle them into one (or a few) to be included in a master template. 

You sound like you have a lot of experience in this arena. For myself the only thing I can think that Sprockets may not have initially been able to do was perhaps compile the newer Typescript .ts file? But looks like there's some ways to make this work now... I just know from experience that a lot of technologies take off in popularity but it's not necessarily because they are the easiest or best tool for the job. Take MongoDB for example, sure it's an awesome solution for special situations but i could never figure out why so many people were using it by default. I thought I just didn't understand something, but then it turns out that basically a lot of people were just jumping on the bandwagon and using MongoDB where a normal relation db like Postgres would be more appropriate. I wonder if some of this dynamic could be occurring in the javascript builder's world, where people are using tools that were perhaps necessary if you *didn't* already have Rails/Sprockets (or PHP, etc) at your disposal. Like users who used Node.js or javascript-only backends (yuck! :-) would need it but is it really necessary for other use cases? will have to see. thanks much for those links though!
