### ISSUE TITLE
Milestone for v4 release?

### ISSUE THREAD

**Issue by bjankord** [rails/webpacker#1713]
Might be helpful to add a milestone for the v4.0.0 release so people can get a sense of where things are at on the project, what all is still left to get in v4.0.0, etc.

**Comment by zernie** [comment]
Agreed, that might prompt some people (including me) to work on the issues that need to be resolved before 4.0.

**Comment by gauravtiwari** [comment]
Thanks @bjankord @zernie for the help. 

I will go through the issues and put them under 4.0 label so we can work on it, thanks again. If you could help clean up the issues list that would be great too.

**Comment by gauravtiwari** [comment]
Made a pre-release (with babel 7 support):

```
yarn add @rails/webpacker@next
bundle update webpacker
```

Any help regarding cleaning up issue list would be much appreciated.

**Comment by RiccardoMargiotta** [comment]
@gauravtiwari Thanks for adding the pre-release instructions and yarn bundle, it made it easy to try out the current `pre.3` release.

A little feedback for you, I spent yesterday afternoon migrating my main project over to take advantage of Webpack 4 and Babel 7, and it's gone pretty smoothly. 


A couple of quirks I came across not really relating to Webpacker, was that I initially forgot that the Babel preset `react` is now `@babel/preset-react`, and I needed to change the `preset-env` config to `"modules": "commonjs"` and `"useBuiltIns": "usage"`. (That first issue was highlighted to me when I ran the [babel-upgrade](https://github.com/babel/babel-upgrade) tool.)

Otherwise, I was able to remove a bunch of code to inline the manifest file, removed specific imports of babel-polyfill as it's now completely handled by preset-env, and I replaced my node modules chunk from the CommonsChunkPlugin with the new SplitChunks:

```js
module.exports = {
  optimization: {
    splitChunks: {
      cacheGroups: {
        commons: {
          test: /[\\/]node_modules[\\/]/,
          name: 'vendor',
          chunks(chunk) {
            // exclude `server_rendering`
            return chunk.name !== 'server_rendering';
          }
        }
      }
    }
  }
};
```

It's working nicely, and with no changes to the main codebase, my JS bundles have been reduced by 15KB (195KB -> 180KB).

Thanks for all your hard work. 👍

**Comment by justin808** [comment]
I just wrote an article on using the pre-release of v4 with React on Rails, including server-side-rendering and concurrent use of the webpack-dev-server.

[Easy React Server Rendering with rails/webpacker v4 and React on Rails
 ](https://blog.shakacode.com/easy-react-server-rendering-with-rails-webpacker-v4-and-react-on-rails-71602276cf4c)

I included a few github repo examples.

💥 

[![image](https://user-images.githubusercontent.com/1118459/47178872-24527800-d2b8-11e8-9140-ee31a7dc0105.png)](https://blog.shakacode.com/easy-react-server-rendering-with-rails-webpacker-v4-and-react-on-rails-71602276cf4c)

**Comment by p0wl** [comment]
Hey, any updates regarding the remaining issues for v4? If they were labeled or assigned to a milestone it would help me for sure.

Thanks for all your work @gauravtiwari, sooo looking forward to v4 (as we can get rid of lots of our customization/plugins)!

**Comment by gauravtiwari** [comment]
Sorry about long silence everyone 🙏 I was away and just got back, will review the remaining issues and PRs. Please give me a few days to settle and make a final release (most probably coming Monday)

**Comment by gauravtiwari** [comment]
Released an RC, please give it a test and if all's well will make a stable release this weekend.

**Comment by jfly** [comment]
Any update on that weekend release? No worries that it's taking longer than expected, just would like to get a sense of when the new release is expected to come out.
