### ISSUE TITLE
Babel/JSX transform not running for JS taken from resolve section.

### ISSUE THREAD

**Issue by Maweypeyyu** [rails/webpacker#1733]
Hi all,

I have a basic rails setup with webpacker and react and issues getting external React components imported.

In my config.js for webpacker configuration:

`resolve.alias = { 'foo': 'bar/baz/' };`

In one of my packs:

`import Test from 'foo/Test.jsx';`

which will lead to a webpack compilation failure:

```
BabelLoaderError: SyntaxError: Unexpected token (6:11)
  return <h1>Test</h1>;
         ^
```

I think the file is not running through babel and/or not through the JSX transformer (does it come from react-rails?)

How can I get this external JSX file imported correctly? I can't bundle/transform it and import it then due to the project environment.

Or is it not possible because it is included via the resolve section? What other solutions would be there in this case?

Thanks for any help and hint in advance,
 Maw

---

Versions (not upgradable):
webpacker = 3.5
rails = 4.2
react-rails = 2.4

**Comment by danielpowell4** [comment]
do you have `@babel/preset-react` (formerly `babel-preset-react`) as a pre-set in your babelrc?

**Comment by gaddevarunteja** [comment]
@danielpowell4 I am facing the same issue, JSX is not getting compiled and throwing unexpected token error.
Even if I use babel-preset-react in babelrc file, I am getting new error related to 'Plugin/Preset files are not allowed to export objects, only functions.'
If I use @babel/preset-react, the jsx is not getting compiled.

I have tried all the options since long time, Any quick help will be appreciated.

**Comment by guillaumebriday** [comment]
Is this still an issue?

Feel free to reopen if needed
