### ISSUE TITLE
Question: Is there anyway to load manifest.json from a remote source?

### ISSUE THREAD

**Issue by babakgh** [rails/webpacker#1798]

**Comment by rsheldiii** [comment]
I think the answer to this question is "no", since `load` uses `public_manifest_path`, which returns a `Pathname`, and 

>Pathname represents the name of a file or directory on the filesystem, but not the file itself.

from https://ruby-doc.org/stdlib-2.5.1/libdoc/pathname/rdoc/Pathname.html

I would like webpacker to support this, since the in-memory manifest would be a little cleaner. I'm using a custom webpack config as I'm migrating a legacy application from webpack-rails to webpack, and this is my current blocker

**Comment by rossta** [comment]
Feel free to open a PR but it looks like you have your answer for what's currently supported.
