### ISSUE TITLE
Webpacker::Manifest::MissingEntryError in Home#index

### ISSUE THREAD

**Issue by KhalidH82** [rails/webpacker#1838]
Webpacker can't find hello_react.js in /Users/khalidhosein/Desktop/myEPKmedia/builder/khalid101/public/packs/manifest.json. Possible causes:
1. You want to set webpacker.yml value of compile to true for your environment
   unless you are using the `webpack -w` or the webpack-dev-server.
2. webpack has not yet re-run to reflect updates.
3. You have misconfigured Webpacker's config/webpacker.yml file.
4. Your webpack configuration is not creating a manifest.
Your manifest contains:
{
  "application.js": "/packs/application-68dcba18197451fbb79e.js",
  "application.js.map": "/packs/application-68dcba18197451fbb79e.js.map"
}

I am getting this error when trying to connect my Rails app with a React front end. I've tried researching and reconfiguring files from all sources. I have also recreated manifiest.json files and packs libraries. I am following this tutorial

https://github.com/natemacinnes/natemacinnes.github.io/blob/master/rails-5-shopify-app-setup.md

If anyone has any ideas it would be greatly appreciated as there isn't much documentation or tutorials out there going over connecting Rails Shopify API with React.

Thanks in advance!

**Comment by KhalidH82** [comment]
@MrHubble No I didn't unfortunately...Are you trying to create a Shopify App with React and Rails?

**Comment by MrHubble** [comment]
No, I was just trying to install `webpacker` on a Rails 5.2 app that had been upgraded from earlier Rails versions. I couldn't get `webpack-dev-server` running because the packages weren't being installed in the `node_modules` folder. After deleting a number of files (including `yarn.lock` that was being created in a directory above the intended directory (ie `/Users/me/) and running `rails app:update:bin` I was finally able to fix my problem. I'm unsure of the exact cause and exact fix. 

Does the following help you with your problem:

![screen shot 2019-01-17 at 2 54 06 pm](https://user-images.githubusercontent.com/2251631/51294714-51095d80-1a68-11e9-8c88-0fd17c4fe96e.png)

https://github.com/rails/webpacker/blob/0d36af9929ac344b8d1d06ad314829f5128d5858/docs/troubleshooting.md#cant-find-hello_reactjs-in-manifestjson

**Comment by rossta** [comment]
Sounds like you found a solution to your problem.
