### ISSUE TITLE
webpack-dev-server vulnerability

### ISSUE THREAD

**Issue by szysza** [rails/webpacker#1873]
Hello,

As the first thing I want to say thank you for doing such a great job with webpacker!

2 days ago we've got the following vulnerability notification https://nvd.nist.gov/vuln/detail/CVE-2018-14732. To actually fix it we need to update the version of `webpack-dev-server` to at least `3.1.11`. I've tried to update it to that version, but it's currently not possible due to the following error when starting the dev server:

```
module.js:549
    throw err;
    ^

Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/node_modules/webpack-dev-server/bin/webpack-dev-server.js:26:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

We use the dev server only locally, so it's not a big problem for us. Never the less it would be great to fix the issue.

**Comment by stefanvermaas** [comment]
I think this can only be fixed by upgrading to the latest (4.0.x) version of `Webpacker` (which is still in beta), because the suggested fix (upgrade `webpack-dev-server` to `^3.1.11`) is not possible because `webpack-dev-server` depends on `webpack > 4.0`.

Might be useful to ask the `webpack` team to also release a `2.x.x` fix.

PS: The first part of the fix would be to add `webpack-cli` to your `package.json`.

**Comment by szysza** [comment]
@stefanvermaas Thanks for the response. Yes, I've tried to use the release candidate version, but since it's a rc it's not stable. I suppose that it's highly unlikely that the `webpack` team will release another fix for the `2.x.x`, because it might be possible that the problem isn't that easy to fix in the old version of webpack. 

I thing that the most reasonable thing to do is to wait, but at the same time wanted to make sure that the issue is known.

**Comment by stefanvermaas** [comment]
I agree, the most reasonable thing is to wait. Helping with getting `Webpacker` ready for version `4.0` is the only thing we can do at the moment.

I see that the Webpack team already answered the question; they won't make a patch for `2.x.x` because `2.x.x` is deprecated. https://github.com/webpack/webpack-dev-server/pull/1603#commitcomment-31236145

**Comment by ale7714** [comment]
@stefanvermaas is there an ETA for when `4.0` would be release? thank you!

**Comment by Yanchek99** [comment]
@stefanvermaas Understood, thanks for the reply.  Wish Github would disregard this vulnerability, the warning there makes it seem more severe than it is.

**Comment by louim** [comment]
@Yanchek99 you can dismiss specific vulnerabilities in your project by going to that specific vulnerability and choosing a reason for the dismissal:
![capture d ecran 2019-01-25 a 11 59 26](https://user-images.githubusercontent.com/923718/51760775-4e76bb80-2099-11e9-877b-ab67e6a9ec65.png)

**Comment by jrochkind** [comment]
> I see that the Webpack team already answered the question; they won't make a patch for 2.x.x because 2.x.x is deprecated. webpack/webpack-dev-server#1603 (comment)

Note that the latest non-beta release of Rails, 5.2.2, will currently create a package.json with:

```ruby
"devDependencies": {
  "webpack-dev-server": "2.11.2"
}
```

When asked to initialize a new app with `rails new appname --webpack`. 

So Rails is installing a deprecated version?  This seems odd. It also seems odd to me that it's creating a package.json with a hard-coded locked `"2.11.2"`, rather than `"~2.11.2"` or `"^2.11.2"`, so no upgrades with `yarn upgrade` are possible without a manual edit of package.json. 

What I understand from this ticket is not only is the current release of Rails creating app skeletons with `rails new` that use a version of webpacker with a CVE -- but there is in fact no supported way to manually use any version of webpacker that doesn't have a CVE with rails either?

This seems to me like an urgent matter, no?

**Comment by guillaumebriday** [comment]
Can this issue be closed ?

**Comment by szysza** [comment]
@guillaumebriday according to https://github.com/nixsolutions/thank-you/issues/35 it can be closed. Thanks.

**Comment by guillaumebriday** [comment]
👍
