### ISSUE TITLE
Vue.js doesn't work in feature tests with the default Rails 5.2 CSP setup

### ISSUE THREAD

**Issue by connorshea** [rails/webpacker#1900]
Rails 5.2.2, Webpacker 3.5.5

I just got stuck on this for about 45 minutes and probably would've been stuck longer if I didn't get lucky and try messing with my CSP configuration.

The README mentions adding an exception to the CSP configuration that will let Vue run with all its development extras in development mode, but then fails to allow `unsafe_eval` in the `test` environment as well.

```ruby
Rails.application.config.content_security_policy do |policy|
  if Rails.env.development?
    policy.script_src :self, :https, :unsafe_eval
  else
    policy.script_src :self, :https
  end
end
```

I'm not sure if there's something wrong with my configuration, as far as I know I'm mostly running what `rails webpacker:install:vue` gave me. Either `unsafe_eval` needs to be allowed for the `test` environment as well, or `test` should use the production Vue.js scripts.

**Comment by connorshea** [comment]
This is what Capybara's `page.html` returned (with some of the unimportant start removed/replaced):

```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
    <!-- Meta tag stuff -->

    <link rel="stylesheet" media="all" href="/packs-test/application-74282cd61cf9994bfc91ea22c04af4a7.css" data-turbolinks-track="reload" />
    <script src="/packs-test/application-0bc3c480ee64b243afa5.js" nonce="" data-turbolinks-track="reload"></script>
</head>
<body>
  <nav class="navbar" role="navigation" aria-label="main navigation">
    Nav stuff
  </nav>
  <div class="container is-fluid mt-20">
    <h1 class="title">Create a new game</h1>

<!---->
  </div>
</body></html>
```

The `<!---->` is what `page.html` actually returned, that isn't modified by me at all. It's where the element that Vue.js hooks into _should_ have been, but Vue was unable to run an inline script to actually place the component.

**Comment by philiplambok** [comment]
Yes, I am also having the same problem with that config, so I changed the config to: 

```rb
if Rails.env.development?
  policy.script_src :self, :https, :unsafe_eval
else
  policy.script_src :self, :https, :unsafe_eval, :unsafe_inline
end
```

This just works well. 

And yes, we use the same configuration since our system testing runs just like the production in the browser (production in https, and testing in localhost:random_port). 

Bye the way I am doing a little research on this problem If we look documentation on https://content-security-policy.com/

Source Value | Description
-----|-----
unsafe_eval|Allows unsafe dynamic code evaluation such as JavaScript eval()
inline_eval| Allows use of inline source elements such as style attribute, onclick, or script tag bodies (depends on the context of the source it is applied to) and javascript: URIs

I think that javascript related issues (vue.js) not in Rails or Webpacker and not the big security problem, so I think that's ok.

But, correct me if I'm wrong.

**Comment by connorshea** [comment]
RE: this config

```ruby
if Rails.env.development?
  policy.script_src :self, :https, :unsafe_eval
else
  policy.script_src :self, :https, :unsafe_eval, :unsafe_inline
end
```

I wouldn't recommend using this because it makes production less secure, which you don't want.

**Comment by DaniG2k** [comment]
I'm having a similar issue (reported in [this SO thread](https://stackoverflow.com/q/59915774/1741325)).

Is there a proper way to fix this or must we make the content security policy unsafe for tests to work? Seems like a really bad option to me.

**Comment by arjunrajkumar** [comment]
Having a similar issue - Vue.js not being rendered on feature test - but tests pass if using Request specs. @DaniG2k Were you able to fix this?

**Comment by DaniG2k** [comment]
Not yet, no 🙁

**Comment by ricvillagrana** [comment]
Same issue here, any suggestions?

**Comment by justin808** [comment]
Is this an issue on v6?

**Comment by justin808** [comment]
Please reopen if still an issue.
