### ISSUE TITLE
RAILS_ENV=test ./bin/rake webpacker:compile fails

### ISSUE THREAD

**Issue by mfazekas** [rails/webpacker#194]
with latest branch

```sh
rails _5.1.0.rc1_ new webpacker-test
cd webpacker-test
echo 'gem "webpacker", github: "rails/webpacker"' >> Gemfile
bundle install
./bin/rails webpacker:install
./bin/rails webpacker:install:react
RAILS_ENV=test ./bin/rake wepack:compile

RAILS_ENV=test ./bin/rake webpacker:compile
Running via Spring preloader in process 95126
Webpacker is installed 🎉 🍰
Using /private/tmp/foo/webpacker-test/config/webpack/paths.yml file for setting up webpack paths
Compiling webpacker assets 🎉
(node:95127) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
Compiled digests for all packs in /private/tmp/foo/webpacker-test/public/packs: 
rake aborted!
Errno::ENOENT: No such file or directory @ rb_sysopen - /private/tmp/foo/webpacker-test/public/packs/manifest-test.json
/Users/boga/.rvm/gems/ruby-2.4.0/bundler/gems/webpacker-afe9f69fd028/lib/tasks/webpacker/compile.rake:16:in `read'
/Users/boga/.rvm/gems/ruby-2.4.0/bundler/gems/webpacker-afe9f69fd028/lib/tasks/webpacker/compile.rake:16:in `block (2 levels) in <top (required)>'
/Users/boga/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.0.rc1/lib/active_support/dependencies.rb:286:in `load'
/Users/boga/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.0.rc1/lib/active_support/dependencies.rb:286:in `block in load'
/Users/boga/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.0.rc1/lib/active_support/dependencies.rb:258:in `load_dependency'
/Users/boga/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.0.rc1/lib/active_support/dependencies.rb:286:in `load'
-e:1:in `<main>'
Tasks: TOP => webpacker:compile
(See full trace by running task with --trace)
```

**Comment by ytbryan** [comment]
`NODE_ENV=test ./bin/rake webpacker:compile` works. 

I believe the frontend packs should be using `NODE_ENV ` instead of `RAILS_ENV`

**Comment by mfazekas** [comment]
>NODE_ENV=test ./bin/rake webpacker:compile works.
no, not really it does not fail, but it compiles to production instead of test

```sh
rm -f ./public/packs/manifest-test.json 
NODE_ENV=test ./bin/rails webpacker:compile 
cat ./public/packs/manifest-test.json 
cat: ./public/packs/manifest-test.json: No such file or directory
```

**Comment by masak2009** [comment]
It's still broken. I don't know where but via capistrano the task assets:precompile will run by hook compiling of webpacker assets and it fails on "No such file or directory - manifest.json". I provide to this command both NODE_ENV and RAILS_ENV.

When I run directly from terminal only webpacker thing then it works:

NODE_ENV=staging RAILS_ENV=staging ./bin/rails webpacker:compile

**Comment by gauravtiwari** [comment]
```NODE_ENV=production RAILS_ENV=staging ./bin/rails webpacker:compile``` try that please 👍

**Comment by masak2009** [comment]
Problem is not in this command (it works!): 

`NODE_ENV=staging RAILS_ENV=staging ./bin/rails webpacker:compile`

Problem was else where. It looks like that if capistrano tried to compile assets in "release_path" then it's fail. When I do monkey patch and redefine assets task by myself to point to "current_path" then it starts to work:

Capistrano deploy.rb (disable capistrano assets:precompile):

```
Rake::Task["deploy:assets:precompile"].clear_actions
namespace :deploy do
  namespace :assets do
    task :precompile_assets_includes_webpack do
      on roles(:app) do
        with rails_env: fetch(:stage) do
          execute "cd #{current_path} && source ~/.profile && nvm use && /usr/local/rvm/bin/rvm ruby-2.3-head@myrails51project do bundle exec rake RAILS_ENV=staging NODE_ENV=staging assets:precompile"
        end
      end
    end
  end
end
```

It does load nvm command via .profile file, setup nvm settings from .nvmrc, use right gemset via rvm files and finally prepompile assets with webpacker. 

You have to have  in you_rails_project/bin file rails and webpack. I forced webpack file inside to use "staging" but it is not important it could work without this change.

It should be nice that webpack compiler print out some info where compiler reading and saving files because now it is blackbox when something not work!
