### ISSUE TITLE
Use `development` as default mode

### ISSUE THREAD

**Issue by kpelelis** [rails/webpacker#1943]
If no specific mode configuration option is provided, Webpacker [falls back to production](https://github.com/rails/webpacker/blob/master/package/environments/base.js#L84). This will also trigger uglification of the code which can in return yield unexpected results in testing (e.g. searching for components that have their names altered) and also increased build times.

I suggest that we change this option to fall back to `development`

**Comment by ro-savage** [comment]
Generally it is better if someone does something wrong with their config, that they get a good production build and slow dev rebuilds. Than a large and slow production app and fast dev rebuilds.

Easy enough for a developer to look into why its slow and figure out they don't have development mode set. (Especially as you said, because the code will look weird in devtools)

**Comment by kpelelis** [comment]
> Generally it is better if someone does something wrong with their config, that they get a good production build and slow dev rebuilds.

That doesn’t make any sense. There is no library that runs production mode by default. Rails doesn’t do it and neither does webpack.

1. Webpacker souls have some sort of parity with the software it wraps.
2. Webpack’s default config is development mode
3. Production builds defeat the whole purpose of running a *dev* server.

**Comment by guillaumebriday** [comment]
If it's ok for you feel free to close this isssue @kpelelis 👍
