### ISSUE TITLE
Circular dependency check should be bundled with Webpacker?

### ISSUE THREAD

**Issue by kapso** [rails/webpacker#1953]
I ran into compile time issue - https://github.com/rails/webpacker/issues/1948

And someone recommended doing a circular dependency check. If this can impact compile performance, shouldn't this come bundled with Webpacker? I am new to the world of React/Webpacker, so was curious.

Maybe bundle this natively? https://www.npmjs.com/package/circular-dependency-plugin

**Comment by connorshea** [comment]
IMO it’d be better to have this mentioned in the docs rather than bundling it by default. It isn’t useful to have in production, so it’d just add an unnecessary dependency.

(Unless there’s a way to have yarn only include a dependency in development? Can devDependencies be specified by packages that’d actually get loaded by the user?)

**Comment by kapso** [comment]
Yea I meant enabling this check in development only. So few possible ways -

- Have a flag in `webpacker.yml` to enable this 
- Or maybe have the `circular-dependency-plugin` enabled in `webpack/development.js`

I am new to the world of Webpacker, so possibly better ways as @connorshea has suggested.

**Comment by guillaumebriday** [comment]
Is this issue still relevant? Feel free to reopen if needed
