### ISSUE TITLE
Vue with Ajax calls

### ISSUE THREAD

**Issue by skazzaks** [rails/webpacker#2087]
First of all, thanks for webpacker!

I have a view that renders a partial that has Vue template code in it, like:

`<profile_modal>

  <template slot="trigger">

    <figure class="profile-card__figure | image -is1x1">
      <img src="<%= person.avatar.url %>" alt="">
    </figure>
...
`

This correctly converts to the appropriate html when rendered as expected. So far so good.

I've recently added AJAX to the page that should rerender this section. I made a js.erb file that uses jquery to repopulate the section of the page that has this data in it.
`$("#my-list").html("<%= escape_javascript(render partial: 'layouts/components/profile-card--modal', collection: @people, as: :person, locals: { content: @people_presenter.profile_modal }) %>"); `

This updates the page successfully, but the rendered output still has the profile_modal tags and thus isn't turned into the code in the template, which means nothing looks right.

Is there a way I can get the Vue code to be interpreted? I saw that you can install and add /packs/my_file.js.erb, but this just threw and error and I am not sure if this is the right way to proceed. It is probably something easy but I just don't know how to approach it. 

Thanks for you help!

**Comment by connorshea** [comment]
This would depend a lot on how you're instantiating Vue. The webpacker docs recommend listening for the `turbolinks:load` or window load event and hooking up the Vue components there. If you're not listening for an event that's emitted by this ajax call, Vue won't know to hook back into the new data you're providing. I'm not 100% sure this would actually work even if you set up the correct events, as it's not really how Vue is supposed to be used anyway. Generally, the Vue component should handle its own state instead of having other JavaScript do it.

Generally, I'd recommend doing this with a method in the vue component itself. You should make the Vue component a [single file component](https://vuejs.org/v2/guide/single-file-components.html) and have a method in the `.vue` file that re-renders the component. If you can have the ajax request inside the vue component itself, that'd be the best solution. Alternatively, just listen for an event that your ajax call will emit and then run the method in your vue component when that event occurs.

You can see how I handle Vue components in my app with webpacker, if that might help: https://github.com/connorshea/VideoGameList

**Comment by skazzaks** [comment]
@connorshea The data is hooked up correctly and the callback works...My rails data shows up on the page after the ajax call. 

What doesn't work is that the Vue specific code (e.g. "<template>") isn't changed to what it should be, but is spit out on the page as if it were valid HTML. The Vue code isn't being changed in the js.erb file like it is in the html.erb file for some reason.

**Comment by skazzaks** [comment]
I would expect the "render partial" code to take the partial and convert it to valid HTML, which happens in the html.erb file which makes the same render call, but which doesn't happen in the js.erb call.

Here is the partial that is to be rendered:

```
<profile_modal>

  <template slot="trigger">

    <figure class="profile-card__figure | image -is1x1">
      <img src="<%= person.avatar.url %>" alt="">
    </figure>

    <div class="profile-card__main">
      <h4 class="header-md | visibility-shift delay-3 property-all duration-5 timing-1"><%= person.offline_name %></h4>
      <% if person.try :title %>
        <h5 class="header-sm -white | mt-1 | visibility-shift delay-4 property-all duration-5 timing-1"> <%= person.title %></h5>
      <% end %>
      <div class="pattern--green | visibility-shift delay-3 property-all duration-5 timing-1"></div>
    </div>

  </template>

  <template slot="image">
    <figure class="profile-card__figure">
      <img src="<%= person.avatar.url %>" alt="">
    </figure>
  </template>

  <header slot="header">
    <h4 class="header-xl"><%= person.offline_name %></h4>
    <h5 class="header-sm -light"> <%= person.try :title %></h5>
  </header>

  <article slot="article">
    <article class="article-copy">
      <% if person.quote.present? %>
      <blockquote>
        <%= person.quote %>
      </blockquote>
      <% end %>
      <% if person.bio.present? %>
      <%= parse_markdown(person.bio) %>
      <% end %>
    </article>
  </article>
<profile_modal>
```

**Comment by jpickwell** [comment]
Can you provide the code that's supposed to be rendering the partial?

If you're using Vue.js, then JQuery is absolutely unnecessary and will only get in your way.

**Personal Opinion Follows:**

If you're only using JQuery for AJAX, then I'd recommend switching to a promise-based library like Axios, or even the Fetch API that's being added to standard JS.

I'm extremely serious about this: JQuery no longer has a place in today's web world, and everyone should stop using it.

**Comment by jakeNiemiec** [comment]
Did you enable the ERB loader?: https://github.com/rails/webpacker#erb

**Comment by skazzaks** [comment]
I think you are right - I am going about this the wrong way by using jquery. Thanks for your help!
