### ISSUE TITLE
Webpacker config that transpiles code to work in IE11?

### ISSUE THREAD

**Issue by gregblass** [rails/webpacker#2115]
I REALLY hate to be that guy - but I've got to say, as a Rails dev trying to get a working ES6 environment that will compile stuff to work in IE11, the documentation to do so could not be more confusing in my wildest of dreams.

Does anyone have a working config example repo out there of a fresh rails app that will transpile arrow functions and other ES6 features to work in IE11?

**Comment by gregblass** [comment]
Feel free to delete this. I think I just didn't understand that webpacker will not magically allow the asset pipeline to transpile ES6. It has to be in javascripts/packs, etc.

**Comment by BookOfGreg** [comment]
@gregblass Webpacker4 comes packaged with Babel7, that actually honors the `.browserslistrc` correctly.
For my project we used stock Webpacker4 and Babel7 configs since they now come with preset-env, and modified the .browserslistrc to include:
```
> 1%
last 3 versions
ie 11
safari 9
```
And added the following polyfills to our JS pack:
```
import "core-js/stable";
import "regenerator-runtime/runtime";
import "whatwg-fetch";
import "dom4";
```

There are still some things you can't do such as special fetch features, some bits of promises, and some bits of shadowdom but 90% of modern JS works in IE11 and Safari with that config.
Hope it helps!

**Comment by gregblass** [comment]
Hey there again! Thanks for the reply man.

This is super helpful. I should have closed this - I’m and idiot and was expecting to be able to use ES6 features in the asset pipeline.

Took me a really embarrassing amount of time to realize that isn’t possible.

Ok the bright side, this example config information should be useful to people.

Cheers!

**Comment by jakeNiemiec** [comment]
@gregblass You should be able to use ES6 features. In order to help debug, could you please post as much as you can of:
- `environment.js`
- `package.json`
- `babel.config.js` 
- `application.js` 
- the full error message (even the parts you wouldn’t think is relevant)

—to a https://gist.github.com. Please tag me via `@jakeNiemiec` in a comment and I’ll be able to point out any problems directly in the gist.
