### ISSUE TITLE
Webpacker::Compiler swallows stdout in the event of failed compilation

### ISSUE THREAD

**Issue by jebw** [rails/webpacker#2190]
In the event of a failed compilation `Webpacker::Compiler#run_webpack` will swallow the output of stdout and only show the output of stderr.

If webpack is incorrectly outputting on StdOut, as seems to be the case with a missing node module, then the user just see's a blank error with no further information

```
Compilation failed:
```

Happy to submit a patch to resolve this - not sure on the best approach? Options I can think of  are

1. Extend line L71 to something like

```ruby
logger.error "Compilation failed:\n#{stdout}\n#{stderr}"
```

2. Log the stdout to a different level in the logger

```ruby
logger.error "Compilation failed:\n#{stderr}"
logger.debug "#{stdout}"
```

Thanks

**Comment by jakeNiemiec** [comment]
Slightly related: https://github.com/rails/webpacker/issues/1677

**Comment by botanicus** [comment]
I can confirm that this indeed occurs frequently (the last case was when I by accident declared already declared `const`) as well as that solutions proposed by @jebw do indeed fix it.

I'm also happy to submit patch, but don't want to steal @jebw's credit.

I suggest this to be treated as a high priority bug, because it makes webpacker pretty much useless.
