### ISSUE TITLE
/* webpackPrefetch: true */ prefetches javascript but doesn't prefetches css

### ISSUE THREAD

**Issue by irbis999** [rails/webpacker#2222]
Hello!
I use Vue and in router i use dynamically loaded components with webpack magic comments.
Route object looks like this:
```
{
    name: 'page',
    path: '/page',
    component: () => import(/* webpackPrefetch: true */ page.vue'),
  }

```
page.vue is a single file component with styles:

```
<template>....</template>
<script>....</script>
<style>
p {color: red}
</style>
```

Webpack prefetches javscript:
`<link rel="prefetch" as="script" href="/packs/js/1-5094bbf096715926b58a.chunk.js">
`
But it doesn't prefetches css file.

Do anyone have an idea how to prefetch css file too?

**Comment by jakeNiemiec** [comment]
The only thing I can think of is to disable `extract_css` in your `webpacker.yml`. This will load your styles with the JS.

The problem is that `webpackPrefetch: true` is part of vanilla webpacks "[magic comments](https://webpack.js.org/api/module-methods/#magic-comments)", webpackER does not have any control over how these function.

**Comment by guillaumebriday** [comment]
Can this issue be closed ?
