### ISSUE TITLE
Keeps deleting style-loader and css-loader

### ISSUE THREAD

**Issue by octoxan** [rails/webpacker#2230]
Just added Webpacker to a fresh Rails install, and then changed one line in  app/javascript/packs/application.js

Added the following: `import "./src/application"` and it finds it just fine in development mode.

When I try running it as production as a test with `rake assets:precompile RAILS_ENV=production` it deletes these folders from node_modules and then errors because it can't find them.

```
EntryModuleNotFoundError: Entry module not found: Error: Can't resolve 'style-loader' in '/home/vagrant/code/example'
```

**Comment by octoxan** [comment]
Also deletes @fullhuman from node_modules every time I run the precompile.

**Comment by gauravtiwari** [comment]
@octoxan Please move these packages under dependencies section of package.json instead of devDependencies including `fullhuman/purgecss`. Anything you need for pre-compilation should be in the dependencies section.

**Comment by jachin** [comment]
I hope this doesn't come off as too whinney... I'm afraid I don't have much Ruby/Rails context but I was just working on the frontend of a rails app and ran right into this issue.

Since webpack is a build tool, it seems like [it should not be required "at run time"](https://medium.com/@dylanavery720/npmmmm-1-dev-dependencies-dependencies-8931c2583b0c).

In my mind having webpack as a `dependencies` list and not the `devDependencies` is saying webpack is required at run time.

Is this a case of two paradigms clashing? `package.json` and `webpack` organize thing 1 way, and the rails build tools organize things a different way, and they don't mesh together just right?

**Comment by jakeNiemiec** [comment]
In my mind having webpack as a dependencies list and not the devDependencies is saying webpack is required at run time.

We _are_ saying: [`webpack` is required at runtime](https://github.com/rails/webpacker/blob/master/docs/yarn.md#add-an-npm-module-to-devdependencies). How else will the remote server compile your assets?
