### ISSUE TITLE
Travis failing 

### ISSUE THREAD

**Issue by smondal** [rails/webpacker#2243]
Any pull request done, travis are failing. Even README file update also failing travis. Here is the log from travis
 
https://travis-ci.org/rails/webpacker/jobs/573902360

yes | rvm @global do gem uninstall bundler --all
ERROR:  While executing gem ... (Gem::InstallError)
    gem "bundler" cannot be uninstalled because it is a default gem
The command "yes | rvm @global do gem uninstall bundler --all" failed and exited with 1 during .

**Comment by jakeNiemiec** [comment]
Thanks for opening an issue. 

It seems to be related to https://github.com/rails/webpacker/pull/2101 by @aried3r. I am not sure what caused it to break now.

https://github.com/rails/webpacker/blob/35924e55938a34ea6033fe4e62e25badd7e88248/.travis.yml#L1-L10

/cc @rails/webpacker

**Comment by aried3r** [comment]
My best guess is that it's RubyGems 3.0.6 and this PR: https://github.com/rubygems/rubygems/pull/2707

Since now `Gem::InstallError` is not caught anymore. I guess this like should also have a `|| true` or we need to find a different way to accomplish this behavior.

Or, we drop Rails 4.2 support and use whatever bundler and rubygems version we wish.

**Comment by jakeNiemiec** [comment]
Thanks all for the quick response 🎊
