### ISSUE TITLE
`stylesheet_pack_tag` should be consistent about whether it produces error (or not) about missing asset regardless of extract_css

### ISSUE THREAD

**Issue by TylerRick** [rails/webpacker#2342]
Would it be okay if we either:

1. make `stylesheet_pack_tag` _always_ simply silently return nil if there is no stylesheet for the given pack name (this is currently the behavior only if `extract_css: false`), or

2. make `stylesheet_pack_tag` _always_ raise a
`Webpacker can't find {pack_name} in public/packs/manifest.json` `Webpacker::Manifest::MissingEntryError` if there is no stylesheet for the given pack name (this is currently the behavior only if `extract_css: true`)

?

[Documentation reference](https://github.com/rails/webpacker/blob/master/docs/css.md#link-styles-from-your-rails-views)

## My workaround

I ended up not running into an error from a `stylesheet_pack_tag` referencing something that wasn't in the manifest until it got to staging. It bugged me that development behaves differently from production. Enough that I changed the `default:` section of my `config/webpacker.yml` to:
```yaml
  # This used to be `false` here and `true` only in production. But then we can't catch errors such
  # as stylesheet_pack_tag referencing something not in manifest until it gets to staging/production.
  extract_css: true
```

I'm not sure yet if there are any downsides to using `extract_css: true` in development (no HMR?), but at least this gives me the same behavior between dev and production...

## Confusion in the community

https://github.com/rails/webpacker/issues/2059#issuecomment-486577228

> However, the problem I've observed with this is that if you have stylesheet_pack_tag in your layout as a default, but your javascript doesn't spit out any styles, then you **will run into an error on live where rails complains about stylesheet not existing**.
> 
> This should be consistent for dev and production environment. As in, **if error is to be generated on production for no stylesheet generated, then development should also give the error**.

https://github.com/rails/webpacker/issues/2059#issuecomment-518485523

> I'm using webpacker with react and, by importing the scss in my `packs/*.js`, the styles work...in development. When I deployed to production, I realized there are no styles available.
> 
> Do I need to add `stylesheet_pack_tag` for it to work in production?
> 
> I think it **would be better if I'd receive any error at any point**.

https://github.com/rails/webpacker/issues/2202:

> This is alright, but [`stylesheet_link_tag`] doesn't raise an error for packs that don't exist ...

**Comment by jakeNiemiec** [comment]
> `stylesheet_pack_tag`should be consistent about whether it produces error (or not) about missing asset regardless of extract_css

`extract_css: false` means that no stylesheet_packs will be created. This is why it will return nil...you don't want styles in the head **and** from your `stylesheet_pack_tags`.

> I'm not sure yet if there are any downsides to using extract_css: true

For codebases with a moderate amount of styling, `extract_css: true` can add 2+ minutes to compile time. This is why it is not recommended for `development`.

Let's continue this in the other issues you opened.

**Comment by bbugh** [comment]
I just spent a couple of hours trying to figure out why production was failing but development works fine. We added a pack and put in the `stylesheet_pack_tag`. Everything was fine, and then production broke when we launched. 

This being a fatal error in production with no warning during development is very surprising. It is a hard to track down error, especially because webpack just reports the name of the pack without a file extension. We thought something was wrong with the JavaScript and just by trying everything possible found out that it was the stylesheet failing.

None of the linked issues from @TylerRick specifically address production having a fatal production error when it can't find a css file. :(

Can we reopen this and address it directly?

**Comment by SampsonCrowley** [comment]
Seriously this is a big problem to think your app is running fine, to find out it's not a silent error in production

**Comment by SampsonCrowley** [comment]
it would be nice if there was a stylesheet pack tag helper that included css *if* it exists, and failed silently if not

**Comment by SampsonCrowley** [comment]
my workaround for anyone looking for a quick fix:

```ruby
# app/helpers/webpacker_overrides.rb
module WebpackerOverrides
  private
    def rescued_pack_tags
      @rescued_pack_tags ||= {}
    end

    def sources_from_manifest_entries(names, type:)
      names.map do |name|
        current_webpacker_instance.manifest.lookup!(name, type: type) unless rescued_pack_tags[name]
      rescue
        rescued_pack_tags[name] = true
        nil
      end.flatten.select(&:present?)
    end
end
```

**Comment by rbclark** [comment]
This issue should really be reopened since this seems to be the only issue that was created by @TylerRick specifically about the inconsistent behavior of `stylesheet_pack_tag`. After trying and failing to use the workaround provided above I'm going to end up just using `extract_css: true` all the time since it provides completely inconsistent behavior.
