### ISSUE TITLE
Rename extract_css to something less ambiguous

### ISSUE THREAD

**Issue by TylerRick** [rails/webpacker#2345]
As this person aptly [pointed out](https://stackoverflow.com/questions/54299581/rails-webpacker-yml-extract-css-option/56307552#56307552), the meaning of "extract" in `extract_css` is a bit unclear and ambiguous:

> ... "extract_css" in webpacker.yml has been a source of confusion for me as well. When it is "extract_css: false" in development and production, a stylesheet IS included in the document head (shouldn't this be "extract_css: true"?). And when I use "extract_css: true", styles are not included in the document.

I'm sure it's probably too late to suggest this, but how about renaming this option to something that is more self-documenting and unambiguous.

Not sure what the best name for it would be...

One idea: `css_from_js_included_via` with value either `automatically_inline_in_head` or `stylesheet_pack_tag`. A bit too verbose, but it would at least better explain what it's doing. :)

**Comment by jakeNiemiec** [comment]
It is called `extract_css` because it extracts `.css` from style imports in `.js` files. 

If you don't extract the `.css`, the styles are loaded alongside your `.js` which injects them into you `<head>` via [`style-loader`](https://github.com/webpack-contrib/style-loader). See docs/css.md for more info.
