### ISSUE TITLE
Why differences in babel config for test env?

### ISSUE THREAD

**Issue by justin808** [rails/webpacker#2429]
Regarding the example babel config files:

Is this necessary: 
https://github.com/rails/webpacker/blob/master/lib/install/examples/react/babel.config.js#L26

and why the setting of `targets.node='current' `for test env only?

This is definitely related: https://github.com/rails/webpacker/issues/416

But I think it's not necessary with newer versions of babel, jest, node, etc.

And simpler is better, generally.

```js
return {
    presets: [
      isTestEnv && [
        '@babel/preset-env',
        {
          targets: {
            node: 'current'
          }
        }
      ],
      (isProductionEnv || isDevelopmentEnv) && [
        '@babel/preset-env',
        {
          forceAllTransforms: true,
          useBuiltIns: 'entry',
          corejs: 3,
          modules: false,
          exclude: ['transform-typeof-symbol']
        }
      ]
```

<img width="1458" alt="2020-01-07_22-09-34" src="https://user-images.githubusercontent.com/1118459/71961681-fd71b180-319b-11ea-888e-a62a0d8b347e.png">

I think just adding this plugin for the test env would do the trick:
```
      plugins.push('@babel/plugin-transform-modules-commonjs');
```

**Comment by jakeNiemiec** [comment]
![image](https://user-images.githubusercontent.com/16782063/72007928-5aab4880-3218-11ea-972d-39ae2d3f08cf.png)

> why the setting of targets.node='current' for test env only?

Users may not be running the `current` release of node. Some temperamental libraries don't yet support new things in `current` since it's the bleeding edge. 

> Is this necessary: `modules: 'commonjs'`

I think so for the following reasons:
- If not set, I think it defaults to ES modules, which are not supported in all versions of nodejs (which jest uses to run). 
- Depending on the version, you need to additionally include the `--experimental-modules` flag

I don't think we will need to worry about this for very long since node@13.2.0 has [removed the flag requirement](https://github.com/nodejs/modules#current-efforts).

**Comment by justin808** [comment]
This issue was well explained by @rossta: [Why doesn't Webpacker use my test config when I run Rails tests?
](https://rossta.net/blog/why-doesnt-webpacker-use-my-test-config-when-i-run-rails-tests.html).

In summary, `NODE_ENV == 'test'` is used to run JS unit tests.
