### ISSUE TITLE
For `yarn add jquery` -- why's there no documentation on what to add to `config/environment.js`?

### ISSUE THREAD

**Issue by ratahtatah** [rails/webpacker#2447]
Why isn't this documented? The only place seems to be some 3rd party source: https://www.botreetechnologies.com/blog/introducing-jquery-in-rails-6-using-webpacker

**Comment by jakeNiemiec** [comment]
I don't think you need to do that. Just make sure that you import jQuery in one of your pack files (eg: `application.js`).

The `ProvidePlugin` can cause more problems than it solves, especially for jQuery since it can break jQuery plugins. This is because the instance of jQuery you are "providing" is different than the one you use in your scripts (`window.$`).

**Comment by ratahtatah** [comment]
Cool, thanks @jakeNiemiec!

All in all this experience has been terribly confusing, especially for me who is a beginner to Rails. Is there any way to make all of this experience easier in the future? Considering Rails enables Webpacker by default, it's kinda odd that it won't work straight outta the box. Perhaps add post-install messages?

Thanks again!

Perhaps add post-install messages
