### ISSUE TITLE
Allow option to not use the included precompile task

### ISSUE THREAD

**Issue by justin808** [rails/webpacker#246]
If [React on Rails](https://github.com/shakacode/react_on_rails) depends on Webpacker, we need to disable the precompile task:

https://github.com/rails/webpacker/blob/master/lib/tasks/webpacker/compile.rake#L21

We have this one:

https://github.com/shakacode/react_on_rails/blob/master/lib/tasks/assets.rake#L34
```ruby
  # These tasks run as pre-requisites of assets:precompile.
  # Note, it's not possible to refer to ReactOnRails configuration values at this point.
  Rake::Task["assets:precompile"]
    .clear_prerequisites
    .enhance([:environment, "react_on_rails:assets:compile_environment"])
    .enhance do
      Rake::Task["react_on_rails:assets:symlink_non_digested_assets"].invoke
      Rake::Task["react_on_rails:assets:delete_broken_symlinks"].invoke
    end
```

Could we make the precompile task from Webpacker optional?

**Comment by gauravtiwari** [comment]
@justin808 I am not sure if majority webpacker integrations would want compile task to be optional. Perhaps, you can clear the `webpacker:compile` task before running `react_on_rails` tasks - `Rake::Task['webpacker:compile'].clear`

If I may suggest, the integrations should base themselves on `webpacker` instead of other way around. Obviously, there will be some issues, and if they are major we can always fix them but this doesn't sound like one.

**Comment by dhh** [comment]
👍 to clearing the task instead.
