### ISSUE TITLE
Possible to support parallel-webpack

### ISSUE THREAD

**Issue by wonderbeel** [rails/webpacker#2479]
Hi guys, looking for ways to improve the build time of one of our company projects I toyed a little with [parallel-webpack](https://github.com/trivago/parallel-webpack) and it drastically reduced our build time from 2.5 minutes to 50 seconds.
Trying to integrate it in our deploy procedure I looked a little around  the code of webpacker and webpack is invoked from [here](https://github.com/rails/webpacker/blob/master/lib/webpacker/webpack_runner.rb) if I am not wrong, so it shouldn't be too difficult to add support for parallel-webpack (maybe with a settings configurable in webpacker.yml?).
Is it doable? I don't know really well the Engines so I am not 100% sure that it will work for them too (it can be really useful for them too), maybe it can be extended to support them too.

**Comment by justin808** [comment]
@iSamuraii can you share your setup used for testing? Did you just modify `bin/webpack`?

**Comment by iSamuraii** [comment]
@justin808 Not yet (it was the next step that I wanted to try, editing `bin/webpack` and caing asets:precompile), I just installed parallels-webpack in the project and invoked it from the cli like this `node_modules/.bin/parallel-webpack --config config/webpack/production.js`.
It compiles correctly every entry that I had declared with wepacker, I only have an issue with the manifest generation probably caused by the parallelized access to the file (but that is already a little hackish to support more than one environment with webpacker).

**Comment by h0jeZvgoxFepBQ2C** [comment]
Did you found a solution for this problem?

**Comment by iSamuraii** [comment]
@h0jeZvgoxFepBQ2C Hi, not exactly I have done a little workaround with a custom rake script, the idea is the following:
- Invoke rails's assets precompilation **without** invoking webpacker to generate the various static assets
- Invoke parallel-webpack directly with and let it write a dedicated manifest for every environment
- Merge all the dedicated manifests in the final one used by rails
It works but I have left it alone because the performance on our server (an AWS EC2 T3.large) are terrible, I did some benchmarks (not a really good test TBH, just some runs) and my guess is that because the number of threads that it can handle isn't really high the performance gain is almost none compared to a serial compilation so this task have sank in priority sadly.
If you are still interested in my solution I can try to clean it a little and share some snippets this evening ;).

**Comment by guillaumebriday** [comment]
I think it will be irrelevant with Webpack 5 and its internal caching system.
