### ISSUE TITLE
How to do TypeScript type checking in 5.1+?

### ISSUE THREAD

**Issue by hueter** [rails/webpacker#2547]
Hello,

I have a TypeScript project and recently [followed the upgrade instructions](https://github.com/rails/webpacker/blob/master/docs/typescript.md) since TS compilation is now [babel instead of ts-loader](https://github.com/rails/webpacker/pull/2449). 

However, I was also using `ts-loader` for type checking during the webpack compilation. In the previous setup, the compiler wouldn't succeed if there was a TypeScript error.

I am wondering how can I get that functionality with the new setup?

Thank you

**Comment by hueter** [comment]
Update -- I think I was able to get it to work with the fork-ts-checker-webpack-plugin via [this helpful issue](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/issues/329)

I would recommend adding this optional step to the TypeScript install / upgrade guide to enable type checking during webpack compilation: 

To enable type checking during complation: 

```sh
yarn install -D fork-ts-checker-webpack-plugin
```

then `config/webpack/development.js`

```js
const ForkTsCheckerWebpackPlugin = require("fork-ts-checker-webpack-plugin");
const path = require("path");

environment.plugins.append(
  "ForkTsCheckerWebpackPlugin",
  new ForkTsCheckerWebpackPlugin({
    tsconfig: path.resolve(__dirname, "../../tsconfig.json"),
    async: false,
  })
);
```

**Comment by connorshea** [comment]
Oh hey, I'm glad that issue is still helpful to people :D

**Comment by seuros** [comment]
> yarn install -D fork-ts-checker-webpack-plugin

you meant ```yarn add -D fork-ts-checker-webpack-plugin```

btw no need to set tsconfig. it will select the tsconfig of the project root folder.

**Comment by snkashis** [comment]
Are there any specific vue instructions/flags we need to flip for this to operate in 5.1+? because the `vue` option in this plugin doesnt seem do the job.

**Comment by somodevo** [comment]
@snkashis I had the same issue. I found out that you need to change your `ForkTsCheckerWebpackPlugin` configuration depending on the Vue version you are using to support TypeScript support in SFCs with `webpacker` >=5.1.

For [Vue 3](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/issues/384#issuecomment-634545180):
```js
new ForkTsCheckerWebpackPlugin({
  typescript: {
    configFile: path.resolve(__dirname, "../../tsconfig.json"),
    extensions: {
      vue: {
        enabled: true,
        compiler: '@vue/compiler-sfc'
      }
    }
  },
  async: false,
})
```

For [Vue 2](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/blame/2a1348d463190b3a75090aa427e64a5ab53f909d/README.md#L289-L293):
```js
new ForkTsCheckerWebpackPlugin({
  typescript: {
    configFile: path.resolve(__dirname, "../../tsconfig.json"),
    extensions: {
      vue: true
    }
  },
  async: false,
})
```

I guess a documentation update would be nice 🤔 I had some trouble updating to `webpacker` 5.1 in a Vue 3 with SFCs + TypeScript setup. Took me some time to find the instructions in the [typescript.md](https://github.com/rails/webpacker/blob/master/docs/typescript.md) after looking for a `v5-upgrade.md` (because [`v4-upgrade.md`](https://github.com/rails/webpacker/blob/master/docs/v4-upgrade.md) exists)

Question to the maintainers: Any thoughts on this? How should a PR look?
