### ISSUE TITLE
How to use css from an npm package - there is not piece of documentation that touches on this

### ISSUE THREAD

**Issue by thebravoman** [rails/webpacker#2552]
1. Migrating to rails 6 
2. Using jquery.fancytree - https://github.com/mar10/fancytree
3. Successfully migrate to using the JS
4. Now has to use the css - 

```
import 'jquery.fancytree/dist/skin-lion/ui.fancytree.less';  // CSS or LESS
```

There is little in the documentation that shares how to use a css from a npm package in a rails view or to refer it in another css document. And this is the second thing we should do when migrating. We should use the js from the npm package and the css from somewhere else which is not the right solution.  

1. New rails 6 apps are not helpful since they use sprockets. 
2. https://github.com/rails/webpacker#usage is about writing a new css.
3. https://github.com/rails/webpacker/blob/master/docs/css.md is trying to touch on the subject of css with "Link styles in your Rails views" and "Add bootstrap", but it is detached  - I guess the "Add bootstrap" should also include more information about he configuratoin for the app/javascript/app.sass

**Comment by jakeNiemiec** [comment]
Try this: `import 'jquery.fancytree/dist/skin-lion/ui.fancytree.css';`

**Comment by salex** [comment]
I'll add my 2 cents!

I've been on an almost 6 month journey tying to move 3 rails applications to rails 6. I'm not a javascript/coffeescript/css/scss expert, I know just enough to get what little I need working. But this has become a lot harder with Webpacker.

[An early issue](https://github.com/rails/webpacker/issues/2413#event-2909684235) was still causing me problems. Adding the `stylesheet_pack_tag` and `require("flatpickr/dist/flatpickr.css"` worked in the first application but I ran into problems with the other two. I moved to stimulus-flatpickr instead of basic flatpickr and still had inconsistency's getting flatpickr working in a staging environment.

The 3 applications all have about the same setup in regards to javascript (converted to stimulus to get rid of jQuery) and CSS (moved to w3-css instead of zurb-foundation, again to get rid of jQuery and the problem zurb had with webpacker). 

The latest 2 application had identical stimulus `index.js` and `pack/application.js` files


```javascript
// controllers/index.js
import { Application } from "stimulus"
import { definitionsFromContext } from "stimulus/webpack-helpers"

import {Autocomplete} from 'stimulus-autocomplete'
import Flatpickr from 'stimulus-flatpickr'
require("flatpickr/dist/flatpickr.css")

const application = Application.start()
const context = require.context("controllers", true, /_controller\.js$/)
application.load(definitionsFromContext(context))

application.register('flatpickr', Flatpickr)
application.register('autocomplete', Autocomplete)
```

```javascript
// pack/application.js
require("@rails/ujs").start()
require("turbolinks").start()
require("@rails/activestorage").start()
require("channels")

import "controllers"
```

The `require("flatpickr/dist/flatpickr.css")` would be picked up and compiled in one application but not the other.

Coping `flatpickr.css` to the assets pipeline worked, but didn't seem like a good idea! 

Little stumbling blocks like not knowing the `require(x.dist.x.css)` must search for the file in the dist directory versus pointing to the actual subdirectory (utils) added to the confusion.

After another day of trying to figure out what was different I ran across this post and did a little more digging using what little documentation is available. I still don't know what was different, a sequence problem on compiling or something only a Webpacker God would know.

I ended up adding a stylesheets directory to the javascript folder and added a `application.scss` file that only contained

```scss
@import "flatpickr/dist/flatpickr.css"
```

Deployed with Capistrono and all is working.

As I said in my initial complaint, a little documentation would help.

**Comment by nguyenj** [comment]
@thebravoman Webpacker is currently using `sass-loader` to handle sass/scss files; from your example, I see that you're attempting to import a `.less` file. You might want to try add and configure `less-loader` middleware.

Once you've done that, you can use the `~` to indicate that the `.less` file you're import is coming from `node_modules`.
Reference: https://github.com/webpack-contrib/less-loader#webpack-resolver

Importing `.css` should also be the same if you're using the `css-loader`.
Reference: https://github.com/webpack-contrib/css-loader#import.

**Comment by nguyenj** [comment]
Referencing the [loaders configuration documentation](https://github.com/rails/webpacker/blob/master/docs/webpack.md#loaders) for quick click.
