### ISSUE TITLE
Consider adding an image_pack_path helper

### ISSUE THREAD

**Issue by Ecco** [rails/webpacker#2562]
This is very useful, for instance to write in inline CSS or to handcraft your own img tag.

Here's the (probably too simple) one I use:

```ruby
def image_pack_path(name)
  asset_pack_path "media/images/#{name}"
end
```

**Comment by SampsonCrowley** [comment]
I don't have time to open a PR, but the monkey patch I have in my app is:

```RUBY
# Computes the relative path for a given Webpacker image with the same automated processing as image_pack_tag.
  # Returns the relative path using manifest.json and passes it to path_to_asset helper.
  # This will use path_to_asset internally, so most of their behaviors will be the same.
  def image_pack_path(name)
    resolve_path_to_image(name)
  end
```

**Comment by SampsonCrowley** [comment]
I found it extremely strange that this isn't already included when the code for it already exists

**Comment by guillaumebriday** [comment]
You can use `image_pack_tag` no ?

```ruby
= image_pack_tag('media/images/name.jpg', class: 'your css class')`
```

You can basically do everything like the classic `image_tag` 👍 

Feel free to close the issue if it's ok for you

**Comment by Ecco** [comment]
> You can use `image_pack_tag` no ?

Well, unfortunately, not always. For example:
```css
background-image: url(#{ image_pack_path('home.jpg') });
```

**Comment by guillaumebriday** [comment]
Hum your example depends on your directory structure. Some people don't want to have their images in the images folder I guess.

I don't think it should be in the Webpacker gem and your helper is pretty straightforward in your code. :)

**Comment by SampsonCrowley** [comment]
@guillaumebriday you seem to be confusing sample code with what is actually necessary to implement. The sample I gave above has nothing to do with keeping images in a specific folder

**Comment by SampsonCrowley** [comment]
@gauravtiwari why did you close this with no input?

**Comment by SampsonCrowley** [comment]
3 lines of code to give users a supported way to access paths that are often generated at compile time without resorting to monkeypatching doesn't seem out of scope to me

**Comment by SampsonCrowley** [comment]
hell it could even be done in one line as an alias if `resolve_path_to_image` wasn't a private method:
```ruby
alias image_pack_path resolve_path_to_image
```

**Comment by SampsonCrowley** [comment]
@guillaumebriday the **current** [`image_pack_tag`](https://github.com/rails/webpacker/blob/d456b1b3783313bf0b3927bed6f434d1de5854c4/lib/webpacker/helper.rb#L52) also relies on the same directory structure before falling back to the given name when calling: [`resolve_path_to_image`](https://github.com/rails/webpacker/blob/d456b1b3783313bf0b3927bed6f434d1de5854c4/lib/webpacker/helper.rb#L189) so I don't see how his **example** (that he literally stated was probably not the correct way anyways) using the default `media/images/...` prefix nullifies this request

From `Webpacker::Helper#resolve_path_to_image`:

```ruby
def resolve_path_to_image(name)
  path = name.starts_with?("media/images/") ? name : "media/images/#{name}"
  path_to_asset(current_webpacker_instance.manifest.lookup!(path))
rescue
  path_to_asset(current_webpacker_instance.manifest.lookup!(name))
end
```

**Comment by guillaumebriday** [comment]
Ok sorry, didn't know that `resolve_path_to_image` is using hardcoded path.

[This](https://github.com/rails/webpacker/issues/2562#issuecomment-621615655) could be next to [this](https://github.com/rails/webpacker/blob/d456b1b3783313bf0b3927bed6f434d1de5854c4/lib/webpacker/helper.rb#L20)

Imo it sounds bit overkill to overload the code with this method because you already can do : 
```html
<img src="<%= asset_pack_path 'media/images/calendar.png' %>" />
```

Your monkey patch sounds good

**Comment by SampsonCrowley** [comment]
@guillaumebriday you *can* do that, but you could also say that about stylesheets, scripts, and any other asset.  I think the real reason this simple addition is worth it is that users *expect* there to be a "correct" way to get the path of mapped assets. it's not a helper that would be difficult to maintain in testing, it doesn't add a lot of bloat, since it's just a portal to an already existing method, `asset_pack_path` *doesn't* automatically find the image with *or* without the `media/image` prefix, and it is a method that most devs will assume already exists; then revert to the *less friendly* `asset_pack_path`

**Comment by SampsonCrowley** [comment]
@guillaumebriday @gauravtiwari I've gotten some more free time lately since this issue was opened, if it would be accepted, I'd be happy to open up a PR sometime this week to add the method I've been using as a monkeypatch in next to [`asset_pack_path`](https://github.com/rails/webpacker/blob/d456b1b3783313bf0b3927bed6f434d1de5854c4/lib/webpacker/helper.rb#L20) (like @guillaumebriday mentioned), with tests of course

**Comment by jamiew** [comment]
Why was this closed? It seems like a simple fix that would make the API more consistent

**Comment by SampsonCrowley** [comment]
@jamiew I think it just never got reopened

**Comment by SampsonCrowley** [comment]
It dropped off my radar since I already patched it in my app so I forgot to open a PR. I'll get it done in the next few days

**Comment by SampsonCrowley** [comment]
@guillaumebriday @Ecco @jamiew well it took way longer than it should've to get around to actually putting it together, but PR has been submitted if you want to go vote for it
