### ISSUE TITLE
Webpacker keeps adding entire library

### ISSUE THREAD

**Issue by woniesong92** [rails/webpacker#2594]
Why does Webpacker import the entire library instead of tree shaking?

### Reproduce

1. Install [antd](https://ant.design/docs/react/introduce)
```
$ yarn add antd
```

2. Import a component in one of the webpacker entrypoints
```
import { Row } from 'antd`
```

3. Compile webpacker
```
$ ./bin/webpack --progress --profile --colors
```

### Expected

Only `Row` component is included in the entrypoint

### Actual

Entire `antd` library is included, making the entrypoint's size >10MB
To avoid this, the only solution I found that works is importing this way:

```
import Row from "antd/es/row";
```

From searching GH, tree shaking is already supported out-of-box and only the selected components should have been imported.

**Comment by rossta** [comment]
Thanks for the detailed report!

> Entire antd library is included, making the entrypoint's size >10MB

Are you looking at a development or production build? 

I would expect development mode to skip tree shaking and production mode to enable tree shaking. My understanding is that Webpacker should meet [the requirements to make webpack tree shaking work](https://webpack.js.org/guides/tree-shaking/#conclusion), so let's confirm whether or not there's an issue with your application.

Compare the output of the following commands, as I did in the demo below, and let me know what you find:

```
$ RAILS_ENV=development NODE_ENV=development bin/webpack
$ RAILS_ENV=production NODE_ENV=production bin/webpack
```

### Demo

I created a branch to my rails6-webpacker-demo repo to illustrate tree shaking with antd using the steps you described: https://github.com/rossta/rails6-webpacker-demo/compare/example/antd-tree-shaking

#### Development build

Here is the output for the development build, which is consistent with what you've described. Note that `js/application-90cc5d416789876ae41a.js` outputs at 6.57 MiB.

```
$ WEBPACK_ANALYZE=true RAILS_ENV=development NODE_ENV=development bin/webpack
Webpack Bundle Analyzer is started at http://127.0.0.1:8888
Use Ctrl+C to close it
Hash: a4b39ccc6798f62ca84e
Version: webpack 4.42.0
Time: 5078ms
Built at: 05/17/2020 9:29:38 AM
                                     Asset       Size       Chunks                         Chunk Names
    js/application-90cc5d416789876ae41a.js   6.57 MiB  application  [emitted] [immutable]  application
js/application-90cc5d416789876ae41a.js.map   6.25 MiB  application  [emitted] [dev]        application
                             manifest.json  364 bytes               [emitted]
Entrypoint application = js/application-90cc5d416789876ae41a.js js/application-90cc5d416789876ae41a.js.map
[./app/javascript/packs/application.js] 10.1 KiB {application} [built]
[./node_modules/moment/locale sync recursive ^\.\/.*$] ./node_modules/moment/locale sync ^\.\/.*$ 3.13 KiB {application} [optional] [built]
[./node_modules/webpack/buildin/amd-options.js] (webpack)/buildin/amd-options.js 80 bytes {application} [built]
[./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 905 bytes {application} [built]
[./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 552 bytes {application} [built]
    + 1457 hidden modules
```
Here is a screenshot of the webpack-bundle-analyzer visualization which includes what appears to be a lot of antd modules:
<img width="1792" alt="antd-development-bundle" src="https://user-images.githubusercontent.com/11673/82148299-64c20100-9821-11ea-8bb8-c69b7cffde43.png">

#### Production build

However, when I run the webpack build in production mode, as it would work with `rake assets:precompile` by default, then the results are different; the overall bundle size is significantly smaller. Note that `js/application-206a8a3a3dffabbf9126.js` is output at 159 KiB.

```
$ WEBPACK_ANALYZE=true RAILS_ENV=production NODE_ENV=production bin/webpack | tee tmp/webpack.log
Webpack Bundle Analyzer is started at http://127.0.0.1:8888
Use Ctrl+C to close it
Hash: b8a41de45e133bc747c9
Version: webpack 4.42.0
Time: 16518ms
Built at: 05/17/2020 9:22:03 AM
                                             Asset       Size  Chunks                         Chunk Names
            js/application-206a8a3a3dffabbf9126.js    159 KiB       0  [emitted] [immutable]  application
js/application-206a8a3a3dffabbf9126.js.LICENSE.txt  420 bytes          [emitted]
         js/application-206a8a3a3dffabbf9126.js.br   43.7 KiB          [emitted]
         js/application-206a8a3a3dffabbf9126.js.gz   50.5 KiB          [emitted]
        js/application-206a8a3a3dffabbf9126.js.map    738 KiB       0  [emitted] [dev]        application
     js/application-206a8a3a3dffabbf9126.js.map.br    156 KiB          [emitted]
     js/application-206a8a3a3dffabbf9126.js.map.gz    186 KiB          [emitted]
                                     manifest.json  364 bytes          [emitted]
                                  manifest.json.br  135 bytes          [emitted]
                                  manifest.json.gz  142 bytes          [emitted]
Entrypoint application = js/application-206a8a3a3dffabbf9126.js js/application-206a8a3a3dffabbf9126.js.map
 [152] (webpack)/buildin/amd-options.js 80 bytes {0} [built]
 [155] (webpack)/buildin/global.js 905 bytes {0} [built]
 [371] (webpack)/buildin/module.js 552 bytes {0} [built]
 [374] ./app/javascript/packs/application.js + 19 modules 44 KiB {0} [built]
       | ./app/javascript/packs/application.js 9.66 KiB [built]
       |     + 19 hidden modules
[1439] ./node_modules/moment/locale sync ^\.\/.*$ 3.13 KiB [optional] [built]
```
Here is the bundle analyzer again. In the antd section, it appears only the `Row` component and its dependencies are imported.
<img width="1792" alt="antd-production-bundle" src="https://user-images.githubusercontent.com/11673/82148470-3e509580-9822-11ea-913d-fc214e5162d0.png">

This demo successfully demonstrates tree shaking in production mode with antd using Webpacker.

### More context

For anyone else landing here, some additional context: tree-shaking works for [`antd`](https://github.com/ant-design/ant-design) because a) it is a library that is written using ES module syntax, so  webpack can statically analyze it (unlike a CommonJS-based lib) and b) it indicated [`sideEffects`](https://github.com/ant-design/ant-design/blob/f45f7353a59873f0fe5dcdcf4e89e7654fce59ef/package.json#L37-L42) which webpack can leverage to determine which non-imported files can be omitted.

**Comment by woniesong92** [comment]
@rossta You're indeed correct. I was able to reproduce the same results: while importing the specific file reduced the bundle size significantly in dev, it was negligible difference on prod.

```
// Both result in same bundle size on prod but different bundle size on dev because tree shaking only works in prod
import { Row } from 'antd`
import Row from "antd/es/row";
```

Thanks for looking into this issue! I'm going to close the issue now and ask you a followup question that's unrelated to this specific issue.
