### ISSUE TITLE
Migrate from node-sass to dart-sass

### ISSUE THREAD

**Issue by JoshRobertson** [rails/webpacker#2673]
Has there been any discussion about migrating from node-sass to dart-sass?

Dart-sass is now the primary implementation of sass, and Webpack itself recommends dart-sass:
https://webpack.js.org/loaders/sass-loader/

**Comment by oshanz** [comment]
This is really important.

1. python2 is now on EOL. node-sass doesn't support python 3. https://github.com/sass/node-sass/pull/2936
2. node-sass has plan to make it deprecate. https://github.com/sass/node-sass/issues/2952

**Comment by justin808** [comment]
Is there any way to monkey patch the child dependency?

**Comment by tegandbiscuits** [comment]
Just wanted to say that #2716 should resolve this.

I'm not sure when it'll actually go out to NPM, but I was able to just replace `@rails/webpacker` with the github repo.

**Comment by SampsonCrowley** [comment]
Can confirm that the current version works just fine... is there any reason the fix for this hasn't been released after a full month?

for googlers, add the following to your package.json dependencies to use the current version that supports dart-sass (replace the commit hash with whichever commit you would like to use, this hash is includes the most recent js fixes):

```json
"@rails/webpacker": "git+https://github.com/rails/webpacker.git#257df41cb17017ab29f1415cf856da494fd93cfc"
```

**Comment by dreyks** [comment]
now that libsass (and hence node-sass) is [deprecated](https://sass-lang.com/blog/libsass-is-deprecated) maybe we should cut another 5.x release with this change?

**Comment by Pezmc** [comment]
How do we go about cutting a new 5.x release, there are a few things now waiting to go out!

**Comment by pedrofurtado** [comment]
https://github.com/rails/webpacker/pull/2914
