### ISSUE TITLE
webpack-dev-server doesn't work with webpack-cli v4

### ISSUE THREAD

**Issue by cxspxr** [rails/webpacker#2776]
rails/webpacker uses webpack-dev-server which is [not compatible](https://github.com/webpack/webpack-dev-server/issues/2759) with freshest webpack-cli. 

Is there any plan to switch to webpack-cli `serve`? Or to provide a guide on how to overcome it

**Comment by MauAbata** [comment]
I just ran into this, and as an extremely dirty hack around it found that adding a script to `package.json` was enough to get things working with the newest webpack-cli.

Since `DevServerRunner`, line ~49 does something like this:
```ruby
        cmd = if node_modules_bin_exist?
          ["#{@node_modules_bin_path}/webpack-dev-server"]
        else
          ["yarn", "webpack-dev-server"]
        end
```

In `package.json`, adding this was enough to get me un-stuck:
```json
  "scripts": {
    ...,
    "webpack-dev-server": "webpack serve"
  }
```

Proper solution might be to find a way to detect which version of webpack-cli is installed in the DevServerRunner and switch out the command used to execute. 🤷

**Comment by excid3** [comment]
Just created a PR to change from `webpack-dev-server` to the built-in `webpack serve` command. 👍
