### ISSUE TITLE
Module errors after upgrade to 6.0

### ISSUE THREAD

**Issue by anark** [rails/webpacker#2840]
After trying to upgrade to webpacker 6.0 I am seeing lots of errors like the following

```
Module not found: Error: Package path ./lib is not exported from package node_modules/use-debounce

Module not found: Error: Can't resolve './utilities' in 'node_modules/graphql'
Did you mean 'index.js'?
BREAKING CHANGE: The request './utilities' failed to resolve only because it was resolved as fully specified
(probably because the origin is a '*.mjs' file or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified
```

Any idea what needs to be changed to fix this?

**Comment by pedrofurtado** [comment]
Hey, @anark ! 👋 

The error persists after these steps below?

1. Upgrade gem and JS package to 6.0.0.beta.4
2. Execute rails webpacker:install

If so, can you provide for us a reproducible repo with the error? It will be more easy for me and webpacker team to debug and find the root cause with you 🔍 🕵️ 

Let me know your results on it 🤝

**Comment by anark** [comment]
This seems to be resolved in the latest beta.6 version.  Thank you so much. Excited for a stable release.
