### ISSUE TITLE
Not all static assets are compressed

### ISSUE THREAD

**Issue by SampsonCrowley** [rails/webpacker#2887]
Not all exensions given in `static_assets_extensions` are ran through brotli and gzip

```yml
static_assets_extensions:
  - .avi
  - .eot
  - .gif
  - .ico
  - .jpeg
  - .jpg
  - .mp4
  - .otf
  - .png
  - .svg
  - .tiff
  - .ttf
  - .webm
  - .webp
  - .woff
  - .woff2
```

![Screenshot from 2021-01-14 17-55-39](https://user-images.githubusercontent.com/22461638/104666769-ec525f00-5691-11eb-99a7-5e4b5b35f885.png)

if any static assets are ran through a compression algorithm, all of them should be.

**Comment by guillaumebriday** [comment]
At this point, only these extensions are compressed: https://github.com/rails/webpacker/blob/5-x-stable/package/environments/production.js#L16

But because other extensions are already compress format, we don't need to compress them again (png for example). 

See: https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/optimize-encoding-and-transfer#text_compression_with_gzip

**Comment by SampsonCrowley** [comment]
While that is true of *some* assets that will be added to the extension list (png for example) that is not true of *all* assets

It doesn't *hurt* anything to compress already compressed file types, but it *does* hurt to *not* compress uncompress file types. The default should be to compress all assets, with an option to skip known compressed types

**Comment by SampsonCrowley** [comment]
@guillaumebriday gzip is also not the only compression method. *Most* browsers support brotli, and brotli is already built in to the gem. There should at least be an option to add additional file types to the compression list

**Comment by SampsonCrowley** [comment]
I would be happy to open a PR of it would be accepted
