### ISSUE TITLE
Can't access webpackConfig values

### ISSUE THREAD

**Issue by anitagraham** [rails/webpacker#2962]
From the [documentation](https://github.com/rails/webpacker#integrations)

If you need access to configs within Webpacker's configuration....
```
const { webpackConfig } = require('@rails/webpacker')

console.log(webpackConfig.output_path)
console.log(webpackConfig.source_path)
```

When I do this in Webpacker (6.0.0.pre.2) the result is 
```
undefined
undefined
```

`console.log(JSON.stringify(webpackConfig, undefined, 2))` does work, but I don't see the paths I want to access there.
(source_path, source_entry_path, public_root_path).

**Comment by rossta** [comment]
Those values don't exist on `webpackConfig` because this object represents the generated webpack configuration and those values are not part of the [webpack config schema](https://webpack.js.org/configuration/). 

There is another object, `config`, that represents the `config/webpacker.yml` as a JavaScript object. 

Try

```js
const { webpackConfig, config } = require('@rails/webpacker')

console.log(webpackConfig.output_path)
```

**Comment by anitagraham** [comment]
Thanks @rossta I will give it another go.
(I rewrote a whole lot of code to use '..' paths last night, but that is easy to fix.
