### ISSUE TITLE
Uncaught TypeError: while integrate old theme with webpacker in rails 6.1.3

### ISSUE THREAD

**Issue by BhadreshC** [rails/webpacker#2970]
Hello,
I was having issues with theme integration in the rails 6.1.3 project.
my theme has all old js and old syntax.

Error
```Uncaught TypeError: $(...).simpleLightbox is not a function```

I know, I did a silly mistake but I can not able to find out it.

Rails     : 6.1.3
Ruby      : 2.7.2
webpacker : 5.2.1

Here is my repo link please find it below and help me out to fix this.
https://github.com/BhadreshC/Template-integration

**Comment by mcmire** [comment]
@BhadreshC I am not 100% on what is happening here, so take this with a grain of salt, but here is my educated guess:

Webpack will look for `require()` statements in your code and pull in the appropriate NPM module that corresponds to the path you're requiring (or reuse a previously-loaded module). It looks like there is such a `require` in https://github.com/BhadreshC/Template-integration/blob/master/app/javascript/external/simpleLightbox.min.js. Therefore, `simpleLightbox` is being added to the object that is exported by saying `require("jquery")`. Note that this is different from the path you are using here: https://github.com/BhadreshC/Template-integration/blob/master/config/webpack/environment.js, where you are using `jquery/src/jquery`. These are both completely separate things. So, although, `simpleLightbox` ends up getting added to _a_ jQuery object, that object is discarded after `simpleLightbox.min.js`, and is not reused in the other files where you are using `jQuery`. Therefore, in order to use this library, I think you will need to either modify it, or create an alias from `"jquery"` to `"jquery/src/jquery"`.

Again, perhaps I am misreading this, but that is what I think is happening.
