### ISSUE TITLE
when is webpacker 6 is expected to release

### ISSUE THREAD

**Issue by kb-ally** [rails/webpacker#2981]

**Comment by mcmire** [comment]
The maintainers can weigh in here if they like, but my observation is that the next version of Webpacker is not tied to the next version of Rails and also has fewer maintainers, so there is no reason for there to be an expected release date. I think unless there is some kind of roadmap published, in general, it is good practice to assume the next version of a piece of software will be released when it is released.

**Comment by DonikaV** [comment]
Could not find gem 'webpacker (~> 6.x)' in any of the gem sources listed in your Gemfile.
My Gemfile
gem 'webpacker', '~> 6.x'

**Comment by anark** [comment]
You would need to add the beta version to your gemfile.

```
gem 'webpacker',  '~> 6.0.0.beta.7'
```

**Comment by DonikaV** [comment]
Ohh... now I have a huge list of errors :D 
I decided to update webpacker because I am trying to update some npm modules and I have an error
![image](https://user-images.githubusercontent.com/26111842/116269326-ce16f780-a786-11eb-94a3-331eb0469daf.png)
But in my wepack config I don't have this option. And this option only exists in webpacker older version.

**Comment by mcmire** [comment]
Might be a better idea to make a new issue rather than add to this one so the conversation doesn't get lost!

**Comment by dhh** [comment]
6.0.0.rc.1 has been released.
