### ISSUE TITLE
JS is executed only when used by `javascript_packs_with_chunks_tag`

### ISSUE THREAD

**Issue by duduribeiro** [rails/webpacker#3073]
Hey Folks 👋 

I'm in a process of upgrading my project from webpacker 5 to webpacker 6.

I've added the `gem 'webpacker', "~> 6.0.0.pre.2"` in Gemfile, executed the bundle and re-executed the webpacker install to regenerate the config files.

I have this `application.js` pack
```
// This file is automatically compiled by Webpack, along with any other files
// present in this directory. You're encouraged to place your actual application logic in
// a relevant structure within app/javascript and only use these pack files to reference
// that code so it'll be compiled.

import Rails from "@rails/ujs"
import Turbolinks from "turbolinks"
import * as ActiveStorage from "@rails/activestorage"
import "channels"

import "alpine-turbo-drive-adapter"
import "alpinejs"

Rails.start()
Turbolinks.start()
ActiveStorage.start()

import "stylesheets/application"

console.log('test')
```

and when I load my packs with `_pack_tag`:
```
    <%= stylesheet_pack_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_pack_tag "application", 'data-turbolinks-track': 'reload' %>
```
my js from the pack is not executed (I don't see it in the log)

but when I load them with `_packs_with_chunks_tag`:
```
    <%= stylesheet_packs_with_chunks_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_packs_with_chunks_tag "application", 'data-turbolinks-track': 'reload' %>
```

it gets executed (I see it in the log). 

I see in the upgrade docs that I should use `_pack_tag` instead of `_packs_with_chunks_tag`

the js is download in both cases. I checked the bundle result and the content is equal in both cases

any idea why this happens?

This is the full patch of the changes I applied:

[upgrade.txt](https://github.com/rails/webpacker/files/6744690/upgrade.txt)

**Comment by rlogwood** [comment]
https://github.com/rails/webpacker/tree/v6.0.0.beta.7

**Comment by nickjj** [comment]
I'm noticing the same exact thing with v6.0.0.beta.7.

Here's a rundown on what I came across:

- Webpacker sees the JS and it correctly picks up the changes as I change my `application.js`
- The `application.js` chunked file gets created by Webpack
- Viewing the source of that file shows all of the JS you would expect (Turbo, your custom JS, etc.)
- None of the JS would execute on the page in all major browsers in regular and incognito mode

The only thing that made it work is changing `javascript_pack_tag` to `javascript_packs_with_chunks_tag`.

Here is a reproduceable example app where the JS wasn't executing as long as you stick to the 0.3.0 release: https://github.com/nickjj/docker-rails-example/tree/0.3.0. The 0.3.0 release here is important because master is going to have the fix applied at some point.

**Comment by duduribeiro** [comment]
Thanks a lot @rlogwood and @nickjj !

Using beta.7 fixed it and now it is working fine 🍻
