### ISSUE TITLE
Dynamic module import with dynamic name

### ISSUE THREAD

**Issue by woto** [rails/webpacker#3075]
Hi, i have a strange behaviour. Could you take a look at it.

```
import('../controllers/example1.js').then(module => {
    console.log(module);
})

let name = '../controllers/example2.js'
import(name).then(module => {
    console.log(module);
})
```

The code of both example files is:

```
export default class {

}
```

Here is the output of `console.log`
![image](https://user-images.githubusercontent.com/146704/124194044-87b87e80-dad0-11eb-9070-fe901a26be20.png)

What's wrong? I found enough discussions and descriptions of problems on the Internet while importing modules with dynamic names. But seems they are at least works with Webpack. But not really sure. But I couldn't make it work in conjunction with Rails + Webpacker + Webpack. Is it a bug or I missed something?

Sincerely yours

**Comment by mcmire** [comment]
@woto The behavior you're seeing is specific to how `import()` works in Webpack. According to the [documentation](https://webpack.js.org/api/module-methods/#dynamic-expressions-in-import):

> It is not possible to use a fully dynamic import statement, such as import(foo). Because foo could potentially be any path to any file in your system or project.

I think the reason why you're seeing what you're seeing is that when Webpack sees an `import()` call in your code it will automatically replace it with the module in question. It does this by statically analyzing the code (parsing it without running it). You can see this replacement behavior by looking at the raw bundled version of your JavaScript file. If you pass an expression to `import()`, however, it isn't able to do anything, so it just skips the call entirely. Your code then runs as-is, and the `import()` call fails because in the context of your bundled code "../controllers/example2.js" isn't a thing.

To fix this, then, you have to pass either a string or a template string to `import()`.

**Comment by woto** [comment]
Yeah thank you. Already forgot about this issue after replacing all dynamic import with a static import :(

I think the most confusing part in this example that at the first sight they are looking same
