### ISSUE TITLE
Unable to run webpacker:install due to nokogiri architecture issue after rails new

### ISSUE THREAD

**Issue by sarambasich** [rails/webpacker#3096]
Hi there,

I'm experiencing an issue where I can't get `rails webpacker:install` to complete successfully after a doing a `rails new` to start a new project. The bundler seems to install x86-64 and arm64 copies of the nokogiri gem. However, this causes an error where the `webpacker:install` step tries to use the arm64 version but my architecture is actually x86_64.

## Environment
* MacBook Pro (2.4 GHz 8-Core Intel Core i9)
* macOS Big Sur 11.4 (20F71) 
* Ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
* Rails 6.1.4

## Shell I/O
[output.txt](https://github.com/rails/webpacker/files/6858819/output.txt)

## Attempted workarounds
* Uninstall `nokogiri` gem
  *  Curiously, I can only remove all installed versions even if I select a specific one from the prompt

## Conclusion
Is there anything I am missing? Or is there way to configure webpacker/Rails to use a specific architecture? Or is this a bug?

Thank you!

**Comment by Eusebius1920** [comment]
What `PLATFORMS` are listed inside your `Gemfile.lock`?

Try to run 
`bundle lock --remove-platform SPACE_SEPERATED_LIST_OF_UNNEEDED_PLATFORMS`

for arm64 this should be (for you) something like

`bundle lock --remove-platform arm64-darwin`

then try `rails webpacker:install` again

**Comment by sarambasich-evi** [comment]
@Eusebius1920 I have listed in the Gemfile.lock:

```
PLATFORMS
  universal-darwin-20
```

I ran the command you provided (`bundle lock --remove-platform arm64-darwin`) and I get this error:

```
Unable to remove the platform `arm64-darwin` since the only platforms are universal-darwin-20
```

Then, I ran the same command except with `universal-darwin-20` instead of `arm64-darwin` and I get this error:

```
Removing all platforms from the bundle is not allowed
```

As a note, I can only run this after the failure I described in the initial post occurs. As there is no Gemfile yet, it is impossible to run this command before executing a `rails new`.

**Comment by Eusebius1920** [comment]
In this case you should run

`bundle lock --add-platform ruby `

first.

I can only try to provide a workaround. I have no MacOS at hand to dig into
the details. But it seems to be rather sone error with bundler.

Potentially you can add a better darwin platform that matches your
hardware. Adding ruby as platform means that gems with native stuff need to
compile on install, wich may take some time.


Stefan Arambasich ***@***.***> schrieb am Do., 22. Juli 2021,
17:29:

**Comment by mcmire** [comment]
This seems like a combination Ruby and Nokogiri issue: https://github.com/sparklemotion/nokogiri/issues/2165 and https://github.com/rubygems/rubygems/issues/4234. It looks like you are using the system Ruby provided by MacOS and the recommended fix at the moment is to use a version manager instead. This is generally a good idea anyway because not only can you install the latest version of Ruby that is compiled just for your system but you won't see the warnings that the output you posted contains around permissions. (See [here](https://mac.install.guide/faq/do-not-use-mac-system-ruby/index.html) for more.) Popular version managers are RVM and rbenv. Once you have one of those installed and have the latest version of Ruby installed, try making a new Rails app again and see if you run into the same issue.

**Comment by sarambasich** [comment]
@mcmire 's solution worked for me. I didn't realize I wasn't using a non-macOS Ruby. Webpacker seems to run successfully after that. Thank you and @Eusebius1920 for your support!
