### ISSUE TITLE
What is the best practice for using jQuery in webpacker

### ISSUE THREAD

**Issue by echoidcf** [rails/webpacker#3118]
First, I have some pages and a layout. 

> which means I should put javascript_pack_tag and stylesheet_pack_tag in the head in the layout, is that right?

Second, I hope each page has its own JS file, and I need different $(document).ready for each page to do some initialization work. Pack them to a bundle is acceptable (which will be load via javascript_pack_tag ), but here comes the problem: all $(document).ready functions are triggered for each single page, even they are not designed for this page. (of course they are, because they all loaded via javascript_pack_tag in the head of layout)

I have several workaround for the problem,
1. use another javascript_pack_tag in each page to load its own bundle. This seems not recommended via readme.md 
2. use something like `<%= javascript_pack_tag @javascript_set || 'application'%>` and set @javascript_set in each controller methods which need a customized $(document).ready. This will work but I am not sure if I should do this. I did not find anybody else using this workaround  in Google Search.
3. in $(document).ready function, try to determinate which is the current page and run its initialization . I think this is not so graceful.

So what is the best practice for using jQuery in webpacker? 
BTW, throw away jQuery is ok, if necessary.

**Comment by mcmire** [comment]
Hi @echoidcf,

First, yes, you can put `javascript_pack_tag` and `stylesheet_pack_tag` in the same places in your layout as `javascript_include_tag` and `stylesheet_link_tag`. `<style>` tags generally go in the head; `<script>` tags can either go in the head or at the bottom of the body.

Second, your `$(document).ready` issue is a common problem when using a single JavaScript file for your entire application. As you've already seen, using a single pack file is a better path than adding multiple pack files, but obviously you need to work around this. A common solution is to assign a data attribute unique to your page to the body element or some container element, and then look for that data element in your JavaScript. If it's there, then you can apply the behavior that's specific to that page, if not, then nothing happens. If you have multiple pages, you'd have multiple sections of your JS responsible for those pages, and each of those would have checks around them. You can choose to split up your JavaScript files, so for instance, you could have one file per page and then import those files in your `application.js`. So you might end up with something like this:

``` javascript
// application.js
import initializeFooPage from "./initializeFooPage";
import initializeBarPage from "./initializeBarPage";

initializeFooPage();
initializeBarPage();

// initializeFooPage.js
export default function initializeFooPage() {
  const $element = $('[data-page="foo"]');
  if ($element.length > 0) {
    const component = new FooPage($element);
    component.render();
  }
}

class FooPage {
  constructor($element) {
    this.$element = $element;

    // attach event listeners here
    this.$element.on('click', () => {
      // do whatever
    })
  }

  render() {
    // change the DOM in some way
    this.$element.addClass('foo');
  }
}
```

Another way to solve this problem is to use a library like [Stimulus](https://stimulus.hotwire.dev/), which is developed by the Rails folks. IMHO, it's a step up from jQuery, as it removes the need for element existence checks and generally provides some nice patterns with which to organize your code.

Hope that helps!

**Comment by echoidcf** [comment]
Thank you for the reply.

So, you suggest the workaround 3: use an unique data attribute to make the view identifiable, and use a `if` or `switch` to handle the initialization work in a GRAND  $(document).ready function?  got it.

And any opinion about workaround 2? Any comment is appreciate.

Write something like in the layout.erb
`<%= javascript_pack_tag @javascript_set || 'application'%>`

Create a foo.js at /javascript/pack/ like
```
$(function(){

  //some initialization work

});
```

And in controller, something like
```
def foo
  @javascript_set = "application,foo"
  #bla bla bla
  render #something whatever
end
```

**Comment by mcmire** [comment]
@echoidcf Sure, you can create a separate pack file per page, too. In a more bare-bones Webpack configuration, typically it is better to have one "entrypoint" (e.g. one application.js in your case) then have separate entrypoints (multiple pack files), but Webpacker adds some configuration for Webpack that eliminates those differences ([these lines](https://github.com/rails/webpacker/blob/5-x-stable/package/environments/base.js#L135-L143) if you're curious). So if it makes more sense for you to have separate pack files for separate pages, then go ahead!
