### ISSUE TITLE
webpacker breaks on node17 with Error: error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by TruePath** [rails/webpacker#3235]
On node 17 running bin/webpack gives me the error "Error: error:0308010C:digital envelope routines::unsupported"  when running webpacker 5.4.3

This is discussed in the webpack issues [here](https://github.com/webpack/webpack/issues/14532) which seems to indicate that it's fixed in the very latest version but that might only be for version 5 of webpack.

**Comment by justin808** [comment]
can you upgrade to v6.rc6?

**Comment by justin808** [comment]
@TruePath I recommend that you don't upgrade to Node 17 yet, and upgrade to webpacker v6 soon.

**Comment by TruePath** [comment]
Thanks.  I mean I have a workaround but I was just trying to be helpful.

And yes, it seems to work fine on rc6 so yah looks like you already got it.

**Comment by bigchickenwings** [comment]
> can you upgrade to v6.rc6?

@justin808 I have upgraded my Webpacker to v6.rc6, but still can't use it with Node.js 18, which is **enforced** by Heroku. Do you happen to know if it really works?

Because if does, I'll insist on this solution a little bit more, but if there's no confirmation, I will probably just look for something else!

**Comment by justin808** [comment]
@bigchickenwings Please try to use https://github.com/shakacode/shakapacker and report there if there are issues.
