### ISSUE TITLE
V6 Status

### ISSUE THREAD

**Issue by justin808** [rails/webpacker#3262]
In case you didn't see it in the README, check out:

https://discuss.rubyonrails.org/t/shipping-webpacker-v6-status/79683.

There will _probably_ not be any official "rails" release of v6.

We will list alternative forks including:

* https://github.com/shakacode/webpackr (https://rubygems.org/gems/webpackr, https://www.npmjs.com/package/@shakacode/webpackr)

**Comment by filipkis** [comment]
Hi @justin808 

I don't see in this discussion anywhere mentioning that there will be no official release. The only thing I see is that it won't be default for rails anymore. 

Second, is the fork in agreement with rails guys. If so, could this original repository point out that it's deprecated and that new stuff is gonna be on your "official" fork. Otherwise, I don't see the reason why not just keep the current repository and hand it over to you or somebody else to maintain (but I do understand if they don't want to do that because if it's under rails then it assumes it's their responsibility). 

Otherwise, thanks for all the great work.

**Comment by justin808** [comment]
Hi @filipkis, let's see what @dhh and @rafaelfranca say.

I'd be happy to adopt the repo.

Either way is OK with me.

I've got many example projects waiting to get updated:

* https://github.com/shakacode/react_on_rails/blob/master/spec/dummy/package.json#L11
* https://github.com/shakacode/react-on-webpacker/blob/main/package.json#L23
* https://github.com/shakacode/react-webpack-rails-tutorial/pull/490/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R30
* https://github.com/shakacode/react_on_rails_tutorial_with_ssr_and_hmr_fast_refresh/blob/master/package.json#L5
* https://github.com/shakacode/react_on_rails_tutorial_with_ssr_and_hmr_fast_refresh/blob/master/Gemfile#L50
* https://github.com/shakacode/rescript-react-on-rails-example/pull/11/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R11
* https://github.com/shakacode/rescript-react-on-rails-example/pull/11/files#diff-d09ea66f8227784ff4393d88a19836f321c915ae10031d16c93d67e6283ab55fR15

and many commercial projects as well.

We all need an "official" v6 to build upon.

**Comment by justin808** [comment]
Credit goes to @dhh for the fork name:

* https://github.com/shakacode/shakapacker
* https://rubygems.org/gems/shakapacker
* https://www.npmjs.com/package/@shakacode/shakapacker
