### ISSUE TITLE
Command "webpack" not found.

### ISSUE THREAD

**Issue by johnbeynon** [rails/webpacker#522]
I'm deploying an upgraded Rails 4.x -> 5.1 app to Heroku and am getting the error

```
Command "webpack" not found.
```

I've gone on to the dyno directly and attempted to run `rake assets:precompile` which fails with the message:

```
Webpacker is installed 🎉 🍰
Using /app/config/webpacker.yml file for setting up webpack paths
[Webpacker] Compiling assets 🎉
[Webpacker] Compilation Failed
yarn run v0.22.0
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

error Command "webpack" not found.
```

This seems to be coming from https://github.com/rails/webpacker/blob/f35331c678c7fd44ef225553629ee3e14989030e/lib/tasks/webpacker/compile.rake#L13

Am I correct in understanding that executing `rake assets:precompile` is all that needs to occur for a deployment? ie, that handles installing the yarn dependencies etc?

I found that if I do `yarn install` first and then `assets:precompile` it works - but I didn't think I had to do that.

```
~ $ rake webpacker:verify_install
Webpacker is installed 🎉 🍰
Using /app/config/webpacker.yml file for setting up webpack paths
```

**Comment by johnbeynon** [comment]
I don't think so.

It shouldn't be necessary to add the node buildpack, Node is already available in the Ruby buildpack.

Heroku invokes `rake assets:precompile` which I believe should be enhanced by webpacker to do the yarn install bit...but that doesn't happen.

**Comment by schneems** [comment]
@ytbryan the buildpack maintainer here. You do not need to use the Node buildpack.

**Comment by ytbryan** [comment]
cc @gauravtiwari what do you think?

**Comment by gauravtiwari** [comment]
@johnbeynon Do you have yarn binstub in your bin folder?

**Comment by gauravtiwari** [comment]
Seems like the task is invoked but there is no yarn binstub present since you were using Rails 4. 

![screen shot 2017-06-20 at 20 33 27](https://user-images.githubusercontent.com/771039/27352219-d5152ca8-55f7-11e7-89cf-252225362ec1.png)

Please regenerate them  - `bundle install --binstubs`

**Comment by gauravtiwari** [comment]
@schneems Do you think it would be better and makes sense if Heroku takes cares of this? Rails with webpacker is essentially a Ruby + Node app  and therefore it should have same deployment behaviour as Ruby and Node buildpack combined.

**Comment by schneems** [comment]
I'm trying to take care of it. We installed Ruby and we installed yarn. I don't know what is failing or why? Do you know where in the code that error message comes from `Command "webpack" not found.`?

I have access to that app (John actually works for Heroku, this is an internal app that he's working for).

I tried generating that binstub, but that file is not generated:

```
$ git status
On branch schneems/rails51
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   bin/rails
	modified:   bin/rake
	modified:   bin/spring

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	bin/_guard-core
	bin/bourbon
	bin/bundler
	bin/coderay
	bin/dotenv
	bin/erubis
	bin/guard
	bin/heroics-generate
	bin/heroku-api
	bin/htmldiff
	bin/ldiff
	bin/listen
	bin/mongrel_rpm
	bin/newrelic
	bin/newrelic_cmd
	bin/nokogiri
	bin/nrdebug
	bin/pry
	bin/puma
	bin/pumactl
	bin/rackup
	bin/rdoc
	bin/ri
	bin/rollbar-rails-runner
	bin/rspec
	bin/ruby-prof
	bin/ruby-prof-check-trace
	bin/sass
	bin/sass-convert
	bin/scss
	bin/sdoc
	bin/sdoc-merge
	bin/sprockets
	bin/thor
	bin/tilt
```

This is in:

```
    webpacker (2.0)
```

**Comment by gauravtiwari** [comment]
@schneems From here - https://github.com/rails/webpacker/blob/master/lib/install/bin/webpack.tt#L23 So the compiler invokes the binstub which tries to run webpack executable using `yarn`

**Comment by gauravtiwari** [comment]
Looks like it's only gets generated with `rails new` (5.1+) - https://github.com/rails/rails/blob/801b33a4812c937a7e726d4060e2e3e9361c56fa/railties/lib/rails/generators/rails/app/templates/bin/yarn

**Comment by schneems** [comment]
Thanks! I manually created `bin/yarn` with these contents:

```
#!/usr/bin/env ruby
VENDOR_PATH = File.expand_path('..', __dir__)
Dir.chdir(VENDOR_PATH) do
  begin
    exec "yarnpkg #{ARGV.join(" ")}"
  rescue Errno::ENOENT
    puts "Yarn executable was not detected in the system."
    puts "Download Yarn at https://yarnpkg.com/en/docs/install"
  end
end
```

Then made the file executable via chmod. After adding to git and deploying, it got rid of this specific error.

Weird that this was required as `yarn` is installed and on the system path.

## Questions

1) Is there a better way to generate that binstub for yarn?
2) If this causes errors (running without a binstub) will future versions that do not use a binstub cause an error? https://github.com/rails/webpacker/pull/367

**Comment by gauravtiwari** [comment]
Ideally, I would suggest to include this behaviour as default like in Node buildpack. 

#367 removed yarn binstub from webpacker in favour of using yarn executable directly on the system. The problem here is the app is generated/upgraded locally where a user either manually runs `yarn install` or `webpacker:install` which basically installs all dependencies but during deployment since `webpacker` doesn't ship with yarn executable anymore the command fails (unless on new Rails 5.1+) 

Until we have a proper solution, perhaps we put back the yarn binstub that was removed in #367 so we don't break the current deployment workflow for users who are either on rails < 5.1 or transitioning to Rails 5.1. 

What do you think?

**Comment by gauravtiwari** [comment]
Oh so it's only problem with Rails 5.1 where `yarn` binstub isn't available for some reason. https://github.com/rails/webpacker/blob/master/lib/tasks/webpacker/yarn_install.rake
https://github.com/rails/webpacker/blob/master/lib/tasks/webpacker/compile.rake#L32

**Comment by schneems** [comment]
I'm not sure. I don't totally know what everything here does.

What does the `bin/yarn` do? It looks like it just converts the `yarn *args*` call to `yarnpkg *args*`.

**Comment by gauravtiwari** [comment]
Yes, it's bit confusing actually - `bin/yarn` shouldn't be there and that's why i removed it in #367. 

The idea was to simply use `yarn` executable directly, which is available by default - both locally and on Heroku. 

You see here - https://github.com/rails/webpacker/blob/f35331c678c7fd44ef225553629ee3e14989030e/lib/tasks/webpacker/compile.rake#L30 we are checking if there is an `yarn:install` task is present (from rails 5.1+) and if not we are enhancing it with webpacker `yarn_install` - https://github.com/rails/webpacker/blob/master/lib/tasks/webpacker/yarn_install.rake

Now if an app is just updated to Rails 5.1 and does't have `bin/yarn` file preset that conditional block will pass because the rails 5.1 has this task already defined however the actual task will fail at runtime because there is no `bin/yarn` file.

**Comment by gauravtiwari** [comment]
For anyone updating from Rails 4.x to 5.1.x to add yarn binstub - 

```bash
bundle config --delete bin
# Will create yarn binstub
rails app:update:bin
git add bin
```

**Comment by gauravtiwari** [comment]
@johnbeynon @schneems Is all okay now? I have documented this in README.

**Comment by johnbeynon** [comment]
Totally happy. Closing.

**Comment by jnfeinstein** [comment]
Currently fighting this issue on Rails 4.2, Webpacker 2, Yarn 1.0.1.  Is there a hotfix for this configuration?  Will updating to Webpacker 3 fix the issue?  Updating to Rails 5.1 is not currently an option.

**Comment by gauravtiwari** [comment]
@jnfeinstein Just install webpacker, `bundle exec rails webpacker:install`. Also you would need to remove ./bin folder from ` .gitignore`

**Comment by jnfeinstein** [comment]
@gauravtiwari thank you for the suggestions.  It appears that adding the `yarn` binstub above fixed the issue.

**Comment by donnfelker** [comment]
Leaving this comment for folks who run across this in the future. My issue was that the version of node I had (`8.0.0`) was too low. I needed, IIRC, `8.9.0` or greater. I upgraded to `11.13.0` and re-ran the commands `rails webpacker:install` commands and all was golden.

**Comment by mtoygar** [comment]
In my case `rails webpacker:install` was silently 'failing'. When I check `node_modules/.bin` folder there was no `webpack` file and this results in the `Command "webpack" not found.` error. [(webpack source code reference)](https://github.com/rails/webpacker/blob/5b481bd710211b6a517da72f30cc3ec76fb35519/lib/webpacker/webpack_runner.rb#L8)

After some investigation, I manually tried to add webpack using `yarn add --dev webpack webpack-dev-server` command and saw the below error(webpack module cant be installed because of some DNS related problem).

`error An unexpected error occurred: "https://registry.npmjs.org/webpack: Hostname/IP does not match certificate's altnames: Host: registry.npmjs.org. is not in the cert's altnames: DNS:a.sni.fastly.net, DNS:a.sni.global-ssl.fastly.net".`

After some research, the above problem is solved with the command below.

`dig https://registry.npmjs.org/webpack @1.1.1.1`

Then, I remove node_modules, and generate it once more using `bundle exec rails webpacker:install`. This time I've had `node_modules/.bin/webpack` file and the error was fixed.

**Comment by jakeNiemiec** [comment]
@mtoygar Glad you could get it working, but remember that webpack should be installed to `dependencies`, not `devDependencies`. `devDependencies` will not be installed in a production environment and have caused problems for webpacker users in the past.

**Comment by mtoygar** [comment]
thank you @jakeNiemiec , `bundle exec rails webpacker:install` adds it to `dependencies` but I will edit and clearify my comment.

**Comment by selivandex** [comment]
You need run task yarn install before assets:precompile.

Look at documentation

https://github.com/rails/webpacker/blob/master/docs/deployment.md

**Comment by dorianmariefr** [comment]
when error happens with capistrano:

```ruby
before "deploy:assets:precompile", "deploy:yarn_install"

namespace :deploy do
  desc 'Run rake yarn:install'
  task :yarn_install do
    on roles(:web) do
      within release_path do
        execute("cd #{release_path} && yarn install")
      end
    end
  end
end
```

**Comment by chrilleferna** [comment]
I followed Dorian's advice (adding a yarn_install to the production.rb deployment file), and that worked. Although I don't understand why this should be necessary at every deployment

**Comment by dorianmariefr** [comment]
i also recommend adding `node_modules` to the `linked_dirs` for faster deploys:

```ruby
append :linked_dirs, 'tmp/pids', 'tmp/sockets', 'log', 'node_modules'
```

**Comment by wdiechmann** [comment]
Had my self a wonderful workbench - until suddenly I got the "webpack not found" virus 😃 

```
diff --git a/Dockerfile b/Dockerfile
index ff1273d..f064077 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -10,7 +10,7 @@ WORKDIR /app/hermes
 # nodejs and yarn
 RUN curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
 RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
-RUN curl -sL https://deb.nodesource.com/setup_15.x | bash -
+RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
 RUN apt-get update && apt-get install -y nodejs yarn
 
```

I downgraded my node to 14.16 (originally c/p'ed a Dockerfile from some post online - and it did actually work wonders for quite some time but then all of a sudden; yeah I know - had to be me right - anyways) and did the "vax and sermon": 

`rails webpacker:install`

\- and in under 5min I was up and running about 😆 

thx
