### ISSUE TITLE
rake yarn:install doesn't seem to do anything

### ISSUE THREAD

**Issue by djforth** [rails/webpacker#564]
When I run rake yarn:install  I was expecting it you run yarn and install packages, but actually did nothing? Is this because the description is incorrect or is the method broken.  

If I run yarn, packages run fine, but if I run rake task I just get  'Running via Spring preloader in process 25949' and nothing happens?

**Comment by gauravtiwari** [comment]
@djforth I get this, perhaps yarn exits since there is nothing to install. Could you add a postinstall script to your package.json and try running the rake task again please?

![screen shot 2017-07-15 at 21 29 04](https://user-images.githubusercontent.com/771039/28242475-a9ac0f3a-69a4-11e7-965f-abd1f51449b1.png)
![screen shot 2017-07-15 at 21 29 46](https://user-images.githubusercontent.com/771039/28242478-bef1b93a-69a4-11e7-8945-ac4563412412.png)

**Comment by djforth** [comment]
Hmm ok interesting, running 'bundle exec rails yarn:install' nothing even when I have removed the node_modules folder , but 'bundle exec rails webpacker:yarn_install' works.

![screen shot 2017-07-18 at 10 22 29](https://user-images.githubusercontent.com/199551/28310012-fda12bfc-6ba2-11e7-980c-44b94efc9a33.png)

I'm running if that helps:
* ruby 2.3.1
* yarn 0.24.6
* webpacker 2.0
* Rails 5.1.2

**Comment by jpickwell** [comment]
`yarn:install` is provided by Rails not Webpacker.
