### ISSUE TITLE
Support test rails enviroment

### ISSUE THREAD

**Issue by codebryo** [rails/webpacker#59]
Hi,

maybe I am doing it wrong, but when I run my specs for the application with rspec,
it still tries to load the `development.js` file.
I tried to create a `test.js` and thought as RAILS_ENV gets picked up by `bin/webpack` anyway it should be fine. But it's not working.
Even if I call `RAILS_ENV=test rspec spec/...` it will be available inside the app, but is ignored by the webpack script.

Am I missing something here?

Best,
Roman

**Comment by dhh** [comment]
We don't have any integration for compiling for tests in webpack at the moment. If you need webpack assets available for testing, then you currently have to compile them yourself.

**Comment by taystack** [comment]
I know this is closed, but I am running into the same issue with running my controller specs. To be clear, should I be putting a command within my `config/environments/test.rb` that runs the webpack executable from `/bin`?

**Comment by stereoscott** [comment]
I'm interested to hear how others got this working. For now we are just running `webpack` before we run our test suite, but it would be nice for to compile automatically before we run the integration tests. Maybe add it to `bin/rspec` or in a `RSpec.configure { |config| config.before(:suite) ... }` block...

**Comment by p0wl** [comment]
We played around with different approaches, e.g. trying to only execute webpack if at least one spec needs it (via `:js` group or similar), but we ended up running webpack `before :suite`:

```
  config.before :suite do
    # Run webpack compilation before suite, so assets exists in public/packs
    # It would be better to run the webpack compilation only if at least one :js spec
    # should be executed, but `when_first_matching_example_defined`
    # does not work with `config.infer_spec_type_from_file_location!`
    # see https://github.com/rspec/rspec-core/issues/2366
    `bin/webpack`
  end
```

for js tests we use jest (and babel-jest for transpiling), so no webpack involved there.

**Comment by zhumo** [comment]
It doesn't seem like the `before(:suite)` would work. Maybe I am doing something wrong and if that's the case, please do let me know! 

I tried before(:suite) and I think what happens is that the backticks kick off a subprocess. So the specs are running while webpack is compiling. Therefore, some specs fail raising that there is no such pack, while others succeed. This success and failure happen non-deterministically. 

The second time that you run the specs, the files have been compiled, so there are fewer failures, but it's not guaranteed that any changes to the files since then will have made it through the compilation.

For now, I'm running `RAILS_ENV=test bin/webpack` before I run the specs. But it'd be great to have a hook in the rspec command line or something else. I wonder, for the 5.1 release, what will the recommended course of action be?

**Comment by taystack** [comment]
@zhumo not sure if you ran into the same problem, but making your change threw an error in `/config/webpack/shared.js` when running `rspec`:
```javascript
const { basename, dirname, join, resolve } = require("path");
//    ^
```
It's kinda smelly, but changing those imports to:
```javascript
const P = require("path")
const basename = P.basename;
// ...
```
seems to fix the symptom. I had to change all files where the unpacking of `require` was done. I would prefer to NOT do this. If anyone has any suggestions I'm all ears. This all feels like a hack to me.

**Comment by zhumo** [comment]
@taystack I did not run in to that issue. I am befuddled as to why that is happening for you because I think `require("path")` is looking at a library external to both rails and webpacker.

**Comment by zhumo** [comment]
@taystack Maybe I found your problem? https://github.com/rails/webpacker/issues/192. If you follow through to the PR, you'll see that it requires node >= 6.4.0.

**Comment by naps62** [comment]
@p0wl In case you're interested, here's a snippet that will only run `bin/webpack` if at least one JS test is run, and only if there's been updates to files in `app/javascript` since the last test build 

https://gist.github.com/naps62/a7dcce679a45592714ea6477108f0419
