### ISSUE TITLE
Questions on the Compiler.rb class

### ISSUE THREAD

**Issue by justin808** [rails/webpacker#647]
Questions referring to the [current version of compiler.rb](https://github.com/rails/webpacker/blob/2397421cc224d8f8aa49b89ebad8023c9164e079/lib/webpacker/compiler.rb) as of writing this issue,

1. If you get 2 requests very close together, how does the compiler.rb know to not try compiling in 2 threads.
2. The code caches the date that the source was last changed as an exact equals compare with the date this is last written. I believe (but I'm not 100% sure) that the manifest will get touched with any compilation, so couldn't we check that the manifest mtime is simply newer than the most recently changed file? 
3. Is there an issue that if a new file is moved to be included, but it's mtime is older than the most recent (does a moved file get updated mtime?), then there is no detection of this change.
4. I'm considering having [React on Rails](https://github.com/shakacode/react_on_rails depend on the compiler.rb. Would having an optional key in the webpacker.yml work? The default is `"#{RbConfig.ruby} ./bin/webpack"`. That string would get replaced by the env dependent config value of `custom_compiler_cmd`. Or we could overload the current `compile` key to allow the new command:

  * true => use default
  * false => do nothing
  * anything else => run this command

**Comment by gauravtiwari** [comment]
1. Yes, this seems like a legitimate issue. We probably need a state on the compiler to keep track of the compilation and perhaps block request until the current compilation is finished instead of triggering multiple compile calls.

2-3. Yeah, this one sounds like chicken-egg, especially for on-demand where we are depending on file mtime to check if source is changed and then trigger compile. Obviously,  in this case manifest.json is always going to be older than source because that's what is being changed. Probably we need something like Spring or Listen to watch for changes instead of just mtime.

4.  Yeah, we have been discussing about this option, which can keep track of current compiler and then perhaps run that compiler as a sub-process of Rails server, which would relieve users from running two processes.

**Comment by justin808** [comment]
> manifest.json is always going to be older than source because that's what is being changed. 

So why not just use the manifest.json timestamp rather than writing a new file?

> Spring or Listen to watch for changes instead of just mtime.

If you want to update on file changes, when not use `webpack -w`?

**Comment by gauravtiwari** [comment]
> So why not just use the manifest.json timestamp rather than writing a new file?

Because manifest.json time is not going to be true in all cases. Consider, where someone makes a change, refreshes the page, which starts the compilation and then went ahead changed another file, and then the manifest.json is going to be newer than source. 

> If you want to update on file changes, when not use `webpack -w`?

Oh that was bit over-though 😄  May be a digest of all files or something that compares not just the mtime but also content. The idea for on-demand is simple i.e. things just works without have to run another process.

**Comment by justin808** [comment]
> So why not just use the manifest.json timestamp rather than writing a new file?

> Because manifest.json time is not going to be true in all cases. Consider, where someone makes a change, refreshes the page, which starts the compilation and then went ahead changed another file, and then the manifest.json is going to be newer than source.

We considered that case, and in the case of using a "webpack -w", one just hits refresh. I do see how this is true for the synchronous case of a file is changed while building, and then the manifest is still newer, so a page refresh won't trigger a recompilation. OTOH, using the "webpack -w" would still result in recompilation.

and

> Oh that was bit over-though 😄 

Not following that comment.

I do like the philosophy of "it just works"

**Comment by gauravtiwari** [comment]
> Not following that comment.

Oh mentioning spring and listen in my comment earlier

> If you get 2 requests very close together, how does the compiler.rb know to not try compiling in 2 threads.

*(updated my comment above)*
`Open3.capture3` call is blocking so it will block all other requests until first compilation is finished therefore don't think we will ever hit this issue**
