### ISSUE TITLE
webpack not picking up yarn packages/modules

### ISSUE THREAD

**Issue by jonhue** [rails/webpacker#699]
[Here](https://github.com/jonhue/webpacker_example) is a default rails app with configuration, issues listed in the README.md file at root level.

Webpack seems to be unable to pick up packages added with yarn. The app just uses the default rails-ujs, turbolinks, actioncable + jquery & jquery-ujs. Adding other packages with yarn has the same effect, this example app just shows how webpacker behaves. (or not behaves.)

**Comment by gauravtiwari** [comment]
@jonhue Made a PR here - https://github.com/jonhue/webpacker_example/pull/1

This issue is not related to webpacker though but how you are importing and using those modules inside your JS files. Webpacker is just a build tool, which uses webpack under the hood to compile and bundle your JS files. 

In future, please consider using Stackoverflow instead of opening an issue here, which is not related to webpacker :)
