### ISSUE TITLE
Use HappyPack by default

### ISSUE THREAD

**Issue by mikecx** [rails/webpacker#701]
I think that webpacker should use [HappyPack](https://github.com/amireh/happypack) by default. It's a simple add-in to the webpack shared config and loaders and speeds up the webpack compiles quite a bit. For me it took the bundle build time from 25s down to 15s.

Thoughts?

**Comment by gauravtiwari** [comment]
HappyPack looks nice but,

- the configuration is bit weird 
- not sure how compatible it is with various webpack versions, 
- and finally, since webpacker as a Gem is going to deal with all kinda of apps - big and small, ideally this should be done in userspace and not something to ship as a default.  

Happy to accept a PR for documenting usage though 👍
