### ISSUE TITLE
Loaders should be sorted

### ISSUE THREAD

**Issue by renchap** [rails/webpacker#748]
In Webpack, the order of loaders is important. They are tested (and applied, if matching) from bottom to top.

With Webpacker 3, all built-in loaders are at the top (because the `loaders` array is build from a `Map`). This prevents the user to easily add a loader at some other place. In my case, I need `worker-loader` at the top, to have the files processed by `babel-loader` and `coffee-loader` beforehand.

A workaround is something like: 

```es6
const workerLoader = new Map()

workerLoader.set('worker', {
  test: /workers\/.*\/?.*$/,
  exclude: /node_modules/,
  loaders: ['worker-loader?inline']
})

environment.loaders = new Map([...workerLoader, ...environment.loaders])
```

but I think Webpacker should provide an easier way, for example sorting on the map keys so I can do something like this:

```es6
environment.loaders.set('01-worker', { ... })
```

**Comment by WoH** [comment]
It's a question of scope. Right now, a good amount of use-cases are fortunately covered :+1: 
Since you can always do environment.getWebpackConfig() and process the object returned, there really is no point where something is impossible to add.

Reversing the Array that gets created from the Map would screw anyone that wants to do pre-processing, which I assume is the more common case. Sorting doesn't seem like a good solution either, using the names as an index sounds like something that will only cause more trouble.

Let's imagine webpacker could provide add/get/update/remove for the plugins and loaders with the option to specify {top: true} to add a loader on top of the list.
If you get by position, the whole thing becomes quite fragile again though (whenever webpacker adds a plugin/loader). If you want to get by name, that would require the Environment to manage the loaders and plugins as an [{name, value}].
I'd work on a CRUD-like functionality if requested, but that would break the current API unless you 
a) patch the Array Prototype or b) create your own class that internally manages an array and provides additional methods, both seem pretty esoteric.

If anyone comes up with a better solution I'm happy to help.

**Comment by javan** [comment]
Thanks, @WoH.

I think your approach is fine for now, @renchap. You could also use `webpack-merge` on the resulting config (`environment.toWebpackConfig()`) if you prefer. https://github.com/rails/webpacker/blob/master/docs/webpack.md
