### ISSUE TITLE
Icon Image file not loading

### ISSUE THREAD

**Issue by ncino-cpezza** [rails/webpacker#784]
When i define `asset_pack_path("images/icon.ico")` and the relative path is set right in the `config/webpacker.yml` file and .ico is listed in the extensions list. What am i missing or is this an extension that needs to be added to the file.js loader in the Packages folder? I get an error saying the file is not in the manifest.json file

**Comment by gauravtiwari** [comment]
`asset_pack_path` only references assets used as pack (i.e. JS packs file) or assets used inside a pack like a font, images or styles referenced that's why it's not present inside manifest.json. `asset_pack_path` doesn't look inside any folder like rails helpers. 

You could reference the ico file inside the pack and then it will be compiled by webpack, which I am not sure is right way since you could do this easily with Rails `image_path` helper.

Makes sense?

**Comment by ncino-cpezza** [comment]
That does yes, would it work if the ico was added to the file.js loader? then mitigating this workaround?

**Comment by gauravtiwari** [comment]
Not sure I understood what you meant? Are you saying to add this to https://github.com/webpack-contrib/file-loader?

**Comment by ncino-cpezza** [comment]
I'm saying add to this https://github.com/rails/webpacker/blob/master/package/loaders/file.js#L6 for test or should it read the config/webpacker.yml file to load extensions to use? May be my ignorance on missing something.

**Comment by gauravtiwari** [comment]
@ncino-cpezza Ahh yes, feel free to make a PR 👍

**Comment by ncino-cpezza** [comment]
ok wanted to make sure i was interpreting it right before a PR :) Thanks! ill do that!

**Comment by gauravtiwari** [comment]
Cool, thanks 👍  🍰

**Comment by ytbryan** [comment]
can this be closed?

**Comment by gauravtiwari** [comment]
Thanks 👍
