### ISSUE TITLE
How to map existing angular-cli app into webpacker structure

### ISSUE THREAD

**Issue by jvkiran** [rails/webpacker#812]
Tried using webpacker-angular, but no result.

I've developed angular-cli app, and rails api, now im using webpacker gem, but how can integrate angular-cli app into existing webpacker

Please someone help....

**Comment by getabetterpic** [comment]
@jvkiran Although we didn't have an existing Angular CLI app, we are using the CLI to build our new Angular stuff. We're putting all of our Angular code in an `app/javascript/angular/app` folder where Webpacker knows to build an `angular` pack with all the source inside the `angular/app` folder.  We also have a `app/javascript/packs/angular.js` file that contains `require('../angular');` which I believe is where Webpacker looks for the packs you want to build. We then have a `<%= javascript_pack_tag 'angular' %>` in our `application.html.erb` to require the Angular pack.

Finally our `.angular-cli.json` file looks something like this:

```json
{
  "apps": [
    {
      "name": "angular",
      "root": "app/javascript/angular",
      "main": "index.ts",
      "test": "test.ts",
      "prefix": "app",
      "tsconfig": "../../../tsconfig.json",
      "polyfills": "polyfills.ts"
    }
  ],
  "test": {
    "karma": {
      "config": "app/javascript/angular/karma.conf.js"
    }
  }
}
```

The key is the `root` option in the `apps` object that tells the CLI where all your files should go. the `../../../tsconfig.json` is because we have our TypeScript config in our root directory. It's all working pretty well for us so far.

**Comment by gauravtiwari** [comment]
thanks @getabetterpic for detailed example 🍰 

@jvkiran Most of the setup should be same as any other angular app built with webpack. The only convention with webpacker is that webpack entry files lives under `app/javascript/packs`. You can structure angular source files anyway you like inside `app/javascript`.
