### ISSUE TITLE
Why not use rake to run webpack-dev-server?

### ISSUE THREAD

**Issue by curvo** [rails/webpacker#831]
I noticed over the weekend that my local version of `./bin/webpack-dev-server` was not actually up to date with the current gem in my project `webpacker@3.0.1`.  I realized then that one would need to run `rake webpacker:install` in order to update the binstubs within my project and that lead me to wondering if it would be possible to run the dev server using rake.  

I now have a fairly simple proof-of-concept working with a new rake task defined within my local version of the webpacker gem.  I can now start the webpack-dev-server using rake which means I don't need an executable file checked into my repo for that.

Was this sort of approach considered at all in the past?  And do you think it would be a possible direction to go?  

It seems to me that minimizing the steps and dependencies for using webpacker will hopefully help to reduce issues over time and make adoption that much easier.

If this is an interesting idea at all I would love to clean things up and offer a PR replacing both the webpack-dev-server and webpack binstub files with rake tasks and removing the dependency of checking those files into all rails repos.

**Comment by gauravtiwari** [comment]
@curvo Thanks for this. 

> Was this sort of approach considered at all in the past? 

No actually, the idea was keep things simple and follow Rails conventions

> And do you think it would be a possible direction to go?

Yeah sounds good, although not sure about using rake task for running things like `dev server` since that's a long running process instead of one off job. Might affect logging etc.  

I have been thinking too on this but didn't get chance to make a PR. The best path would be to ship bins as GEM executables so this can be updated and loaded using `bundle binstubs webpacker` when needed but the actual binary would live inside the GEM so internal code changes won't affect the behaviour (much like Rails or Rake binstub)

**Comment by curvo** [comment]
@gauravtiwari @rossta - Thanks for the update and awesome turn-around!
