### ISSUE TITLE
Is it possible to get server variable in xx.vue.erb file? 

### ISSUE THREAD

**Issue by GreatVincy** [rails/webpacker#845]
My rails project is now integrated with webpack and runing well,
but I want to use vue single file components as following:
> in view file (xxx.html.erb)
```
<%= javascript_pack_tag 'xxx.js' %>
......
<div id="el">
  <App></App>
</div>

```
> in vue component file (xxx.vue.erb)
```
<template>
  <div>
   <!-- current_user is a rails global variable -->
    <p><%= current_user %></p>
  </div>
</template>
<script>
  export default {
    data () {
      return {
      }
    }
  }
</script>
```
> in enrty file (xxx.js)
```
import  App from 'xxx.vue'
new Vue({
  el: '#el' ,
  components: {
    'App': App
  }
})
```
Unexpectedly, it not work!
Although doing so did not cause any error in webpack and browser，
I can't see the **current_user** variable in the browser and the content of **\<p\>** tag was blank.
Is there a way to deal with this problem?

**Comment by gauravtiwari** [comment]
@GreatVincy Here is documentation on passing props from view to vue components: https://github.com/rails/webpacker/blob/master/docs/props.md

`current_user` is not passed to view context inside erb files that's why it's not available. If I may suggest, may be don't use erb and just pass data you need from the view directly into your component or you can even fetch on mount from server via ajax.
