### ISSUE TITLE
3.0.2 release for High Sierra Launch 9/25?

### ISSUE THREAD

**Issue by aselder** [rails/webpacker#848]
With High Sierra set to release on Monday, should a 3.0.2 release be cut with the High Sierra fix?

**Comment by gauravtiwari** [comment]
@aselder Please use master branch that has High Sierra fix for time being. We are thinking to make another release sometime next week but can't say it will be on Monday :)

**Comment by Superpencil** [comment]
Working master branch works!
`gem 'webpacker', github: 'rails/webpacker'`

**Comment by cavneb** [comment]
This doesn't seem to work well when deploying to Heroku. It would give me errors like this:

`Sprockets::FileNotFound: couldn't find file 'jquery-deparam/jquery-deparam.js' with type 'application/javascript'`

**Comment by Superpencil** [comment]
@gauravtiwari Please reconsider being sparse with your release regarding this issue, at the moment we our programmers gitignoring their own gemfiles in an effort to keep our prod code clean

**Comment by gauravtiwari** [comment]
@Superpencil Please forgive me, the plan was basically that. Please expect a release this week once Javan is back.

**Comment by kstratis** [comment]
In High Sierra I just start my app with rails s I get: 

```ruby
ActionController::RoutingError (No route matches [GET] "/packs/filename-90e3a229dfb65ab02cae.js"):
```

However if I first do: `bin/webpack-dev-server` and then in a second window do `rails s` all seems to be working great.

**Comment by gauravtiwari** [comment]
@kstratis Make sure compile is set to true, if you don't want to use dev server and use on-demand compilation instead. It's under `config/webpacker.yml`

**Comment by kstratis** [comment]
@gauravtiwari `compile` is already set to true in both development and test environments. However I still get this no matter which route I hit:  

```ruby
Started GET "/packs/datatables-bundle-90e3a229dfb65ab02cae.js" for 127.0.0.1 at 2017-10-03 13:32:03 +0300

ActionController::RoutingError (No route matches [GET] "/packs/datatables-bundle-90e3a229dfb65ab02cae.js"):

actionpack (5.1.4) lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
...
```

I also forgot to mention that I am using the latest react_on_rails 9.0.3.

**Comment by gauravtiwari** [comment]
@kstratis Right, have you tried just with Webpacker. It could be that the `react_on_rails` isn't using on-demand compilation from webpacker.

Works like this basically: 
![screen shot 2017-10-03 at 11 36 52](https://user-images.githubusercontent.com/771039/31121218-38cc0d46-a82f-11e7-94be-56d4469572f3.png)

**Comment by kstratis** [comment]
@gauravtiwari Thanks for pointing me in the right direction. It turned out that indeed Webpacker was not doing the on-demand compilation. 

The solution was to just delete the temp folder in my Rails app and then restart the server as pointed out [here](https://github.com/reactjs/react-rails/issues/171#issuecomment-247619806). 

For the record this happened only after upgrading to High Sierra.

**Comment by gauravtiwari** [comment]
@kstratis No worries. Ahh I see, that's another way but usually you don't have to do that if you are just using on-demand compilation. 

It's possible that the timestamp of the files haven't changed since you upgraded to Sierra and may be you have run dev server at some point, which could have changed the manifest.json and hence the error - `pack not found`. 

If you run `webpack-dev-server` after on-demand compilation and switch back to on-demand then it won't re-compile unless a file is changed so, in that case you would need to delete the cache to force recompile otherwise you will get `404 not found` since the manifest has changed.
