### ISSUE TITLE
Coffeescript dependency does not accept Coffeescript 2.0

### ISSUE THREAD

**Issue by renchap** [rails/webpacker#868]
`@rails/webpacker` depends on `coffeescript@^1.12.7`
Coffeescript 2 has been released with a lot of new features: http://coffeescript.org/announcing-coffeescript-2/ (JSX support, …).
Would it be ok to either bump the dependancy to 2.0, or at least accept it?

CS2 outputs ES6, so it needs to be transpiled using Babel (see #859).

Currently I have both 1.12.7 installed and 2.0.1 (from my own `package.json`), but `coffee-loader` loads the 1.12.7 version. It worked fine previously but just broke, and I can not figure out why (it loaded 2.0.1 before, and suddently decided it would revert to loading 1.12.7).

**Comment by gauravtiwari** [comment]
@renchap Apologies, totally forgot to reply on #859 

I am not sure really, considering there will be people who are still stuck on legacy code and people who want to use CS2. That's why I felt that moving all this to user space would be lot easier like React and other integrations, so we don't have to bump deps.

But anyway, for now I think we can conditionally bootstrap coffee loader like we do with `style` loader (hmr vs non-hmr) so it works with both CS1 and CS2.

**Comment by renchap** [comment]
Would it work to not have `coffeescript` in dependencies, so the user can choose which version he wants? Or put it in `peerDependancies` maybe?

**Comment by gauravtiwari** [comment]
Yeah, that's what I was thinking - to not have `coffeescript` as dependency like React and other stuff. We just have to make it clear to install `coffeescript`. In Rails world, we do this for gems like `mysql` or `pg` - that's all in user space.

**Comment by renchap** [comment]
Ok. Is it a way to check if a package is installed to conditionally add `coffee-loader`?

**Comment by gauravtiwari** [comment]
Made a PR here: https://github.com/rails/webpacker/pull/870. Please take a look
