### ISSUE TITLE
Webpacker:Vue component styles do not work

### ISSUE THREAD

**Issue by sdellis** [rails/webpacker#987]
First of all, the path to `app.vue` is incorrect in `app/javascript/packs/hello_vue.js` for the commented out section below (needs an extra dot). It also doesn't seem to work when the path is corrected. Here's [an example](https://github.com/sdellis/webpacker-test).

I was able to get the components to work [here](https://github.com/sdellis/filemanager-rails-example), but none of the component styles render. I had to put them in `app/assets/stylesheets/` 

Am I doing something wrong or is this a bug?

**Comment by sdellis** [comment]
I added the `stylesheet_pack_tag` based on the [answer in this Stack Overflow question](https://stackoverflow.com/questions/46310539/rails-5-1-app-does-not-seem-to-load-vue-component-css), which got me closer. I then removed `scoped` and `lang="scss"` from the component styles (i.e. `<style lang='scss' scoped>`). This seemed to do the trick. Seems like it could still be a problem for some, but this will allow me to move forward with Webpacker in my project.

**Comment by ytbryan** [comment]
If this is a non-issue, maybe you can close it.

**Comment by sdellis** [comment]
I don't think it's a non-issue, but I found some workarounds. Closing now.

**Comment by rlafranchi** [comment]
@sdellis, @ytbryan  - I could submit a pr to improve documentation.

ex.
## Using CSS with [vue-loader](https://github.com/vuejs/vue-loader)

Vue templates require loading the stylesheet in your application
in order for CSS.  This is in addition to loading the JavaScript file for
the entry point.  Loading the stylesheet will also load the CSS for
any nested components.

```erb
<%= stylesheet_pack_tag 'hello_vue' %> 
<%= javascript_pack_tag 'hello_vue' %>
```

**Comment by ytbryan** [comment]
Yes, thank you... please send the PR @rlafranchi

**Comment by gauravtiwari** [comment]
Yes, lets document this 👍

**Comment by RobPando** [comment]
@sdellis @ytbryan This is being an issue for me, I had to do in-line styling for now which is killing me. I have the `stylesheet_pack_tag` in and also removed `scoped` (I didnt have `lang='css'`) but all this still didnt do the trick for me. Can this be re-open? Im on web packer 3.0.2, Vue 2.5.3, vue-loader 13.5.0 and vue-template-compiler 2.5.3

**Comment by ytbryan** [comment]
cc @rafaelfranca

**Comment by gauravtiwari** [comment]
@RobPando Could you please post an example repo to reproduce this?

**Comment by RobPando** [comment]
@gauravtiwari Its an open source project so actually this is the exact repo I am having problems with: https://github.com/MustardSeed/Fraternos/ and the Vue component is here https://github.com/MustardSeed/Fraternos/blob/master/app/javascript/components/meetings_calendar.vue

**Comment by rlafranchi** [comment]
@RobPando - at first glance it looks like your using an npm package `vue-event-calander` which requires CSS import.  Try adding `import 'vue-event-calendar/dist/style.css'` to your packs/meeting_calendar.js file.

**Comment by RobPando** [comment]
@rlafranchi Is being imported in assets/stylesheets/_base.scss. I just moved it to where you suggested and it made no difference, 😞 the styles are still not being picked up.

**Comment by gauravtiwari** [comment]
Seems to work fine per style provided: 

![events-calendar](https://user-images.githubusercontent.com/771039/32797108-9f5b6688-c968-11e7-939a-b2b6d217404d.gif)

This is the default template: https://github.com/GeoffZhu/vue-event-calendar/blob/master/README.zh.md

**Comment by gauravtiwari** [comment]
This is using styles from sprockets import

**Comment by RobPando** [comment]
@gauravtiwari It didn't make sense to me that the component ignored custom classes, but I guess it does. My bad completely. Thanks for pointing this out regardless being a non webpacker issue,  I appreciate the help, you guys are awesome.

**Comment by olingern** [comment]
I just stumbled across this. 

It doesn't make a lot of sense for [single file components](https://vuejs.org/v2/guide/single-file-components.html) to have to include to tags for webpacker a stylesheet + javascript file.

**Comment by alecjacobs** [comment]
Adding this

```
...
<head>
  ...
  <%= stylesheet_pack_tag 'application' %> 
  ...
</head>
...
```

to `app/views/layouts/application.html.erb` seems to work for webpacker/rails/single file components/etc

**Comment by svilenkov** [comment]
I've just found out that if you don't have any <style> tags in your component and you are using the helper `stylesheet_pack_tag 'application'` for importing css from js (eg. vue components), the same error will appear. So you should have at least 1 `<style>` tag somewhere along the import line in your main js entryfile.  The <style> tag needs to have some content, even just a comment, at least that's how it behaved for me.

It can be really confusing when this happens, i had just a few components for testing, removed all the style tags, because a CSS framework classes were sufficient, then tomorrow when I re-run the app suddenly this strange time consuming error :)

**Comment by crashspringfield** [comment]
@svilenkov can you provide an example of this? I don't quite understand your explanation.

**Comment by svilenkov** [comment]
@crashspringfield 
> @svilenkov can you provide an example of this? I don't quite understand your explanation.

I don't remember the details of the problem now. I remember there was an issue when using Vue single file components (https://vuejs.org/v2/guide/single-file-components.html)

Adding an empty <style> tag this caused some issue. Maybe there were missing styles from other vue single file components or it was displaying some kind of an error...
```vue
<style>
</style>
```
The issue was solved by having some text content within the body of the <style> tags in single file components:
```vue
<style>
/* at least 1 of you .vue files must have some text content within the <style> tag, even just a comment */
</style>
```
Sorry can't remember the actual error/misbehavior.

Another thing, perhaps unrelated, which I remember is that using the same name for 
`stylesheet_pack_tag` and `javascript_pack_tag` caused the app's js bundled output file to become empty, providing different names solved that issue

**Comment by gnclmorais** [comment]
Regarding the issue @svilenkov pointed out, I’m trying to figure out if it’s a bug or a feature… I’m also interested in knowing of a way to always output the corresponding CSS file, even if empty because the components have no CSS yet (instead of adding the add a comment like @svilenkov suggested). Any ideas?
