### ISSUE TITLE
bin/webpacker-dev-server not optional

### ISSUE THREAD

**Issue by bbuchalter** [rails/webpacker#988]
Although there are many references to the webpacker-dev-server being optional, the presence of `bin/webpacker-dev-server` is [enforced](https://github.com/rails/webpacker/blob/105c9e8d11a70b8f6f5f7d5232537665599bfc4a/lib/tasks/webpacker/check_binstubs.rake#L4) by the `check_binstubs` rake task.

Is there interest in making this guard more intelligent? Just remove it? Or be OK with folks adding dummy binstubs?

**Comment by gauravtiwari** [comment]
@bbuchalter Are you facing any issues due to it's presence? Please consider removing it manually if not needed - `rm -rf bin/webpack-dev-server`.

**Comment by bbuchalter** [comment]
> Are you facing any issues due to it's presence?

Well, I removed webpack-dev-server from my stack because of recent changes that many people are complaining about [0] and it just doesn't make sense to leave the file in the repo.

[0]: Just a few issues opened recently on one topic in particular that seems to impact the Rails community in particular:
webpack/webpack-dev-server#1170
webpack/webpack-dev-server#1144
webpack/webpack-dev-server#1143
webpack/webpack-dev-server#1136
webpack/webpack-dev-server#1101
webpack/webpack-dev-server#1104
webpack/webpack-dev-server#1084

**Comment by stewart** [comment]
Hi there!

For some additional context, we ran into the issues @bbuchalter noted with `webpack-dev-server` a short while back, and decided to remove it from our project, as we weren't getting significant benefits from it, and downgrading caused further issues.

However, after removing the associated binstub (`bin/webpack-dev-server`), we found we were no longer able to deploy our application, as webpacker's extension of the `assets:precompile` Rake task adds the `webpacker:check_webpack_binstubs` task as a dependency. This blows up, as we removed the dev server binstub.

Our (hopefully temporary) solution to this problem is an empty binstub that exists only to satisfy this one Rake task.

I believe that this check is overly aggressive, as `webpack-dev-server` is an optional component of a Webpack environment, and is _certainly_ not needed to precompile assets. If a PR to modify the `check_webpack_binstubs` Rake task to remove this assertion is welcome, please let me know.

**Comment by gauravtiwari** [comment]
@stewart Yeah, makes sense. Lets make `webpack-dev-server` binstub optional.

**Comment by ketan** [comment]
Is someone working on this PR, if not I think I can whip one up. It's affecting me as well.

**Comment by ketan** [comment]
Oh well, #1012, seemed straight forward :)

**Comment by bbuchalter** [comment]
Thanks for helping move this forward! ❤️
